# 🛒 Multi-Site Laptop Scraper
### Noon · Amazon · Jumia (Egypt)

### Made By: Eng. Elsayed Bakry
This notebook scrapes laptop listings from **Noon**, **Amazon**, and **Jumia** Egypt.

**How to use:**
1. Run **Cell 1** once to install dependencies.
2. Run **Cell 2** to import libraries.
3. Run **Cell 3** to define the shared `extract_specs` helper.
4. Run **Cell 4 / 5 / 6** for whichever site(s) you want — each is fully independent.
5. Run **Cell 7** to merge all scraped data into one CSV.

> ⚙️ **Settings** — change `MAX_PAGES` (default **10**) and `OUTPUT_FILE` at the top of each scraper cell.  
> 🔇 To run without opening a browser window, uncomment the `--headless=new` line inside `get_driver()`.

## Cell 1 — Install dependencies
Run this **once**. Skip on subsequent runs if packages are already installed.

In [1]:
!pip install -q selenium pandas webdriver-manager

[notice] A new release of pip is available: 25.2 -> 26.1.1
[notice] To update, run: C:\Users\5g\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Cell 2 — Imports
Standard libraries used by every scraper below.

In [2]:
import re
import time
import pandas as pd

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

print("✅ Imports ready")

✅ Imports ready

## Cell 3 — Shared helpers
Two reusable functions used by every scraper:

- **`get_driver()`** — launches a Chrome browser with anti-bot settings.  
- **`extract_specs(title)`** — parses RAM, storage, screen size, CPU, and GPU from a product title using regex.

In [3]:
# ─────────────────────────────────────────────────────────────────
# get_driver() — returns a configured Chrome WebDriver instance
# ─────────────────────────────────────────────────────────────────

def get_driver():
    """Launch Chrome with settings that reduce bot-detection."""
    options = Options()

    # Uncomment the next line to run without opening a browser window:
    # options.add_argument("--headless=new")

    options.add_argument("--start-maximized")
    options.add_argument("--disable-blink-features=AutomationControlled")
    options.add_experimental_option("excludeSwitches", ["enable-automation"])
    options.add_experimental_option("useAutomationExtension", False)

    driver = webdriver.Chrome(
        service=Service(ChromeDriverManager().install()),
        options=options
    )
    # Mask navigator.webdriver flag
    driver.execute_cdp_cmd(
        "Page.addScriptToEvaluateOnNewDocument",
        {"source": "Object.defineProperty(navigator, 'webdriver', {get: () => undefined})"}
    )
    return driver


# ─────────────────────────────────────────────────────────────────
# extract_specs(title) — parses spec fields from a product title
# ─────────────────────────────────────────────────────────────────

def extract_specs(title):
    """
    Extract hardware specs from a laptop product title using regex.

    Returns a dict with keys:
        screen_size, processor, ram, storage, gpu
    Any field not found in the title will be None.
    """
    specs = {
        "screen_size": None,
        "processor":   None,
        "ram":         None,
        "storage":     None,
        "gpu":         None,
    }

    if not title:
        return specs

    # RAM — e.g. "16GB RAM"
    m = re.search(r'(\d+)\s?GB\s?RAM', title, re.I)
    if m:
        specs["ram"] = m.group(1) + "GB"

    # Storage — e.g. "512GB SSD" / "1TB HDD"
    m = re.search(r'(\d+\s?(?:TB|GB)\s?(?:SSD|HDD|NVMe))', title, re.I)
    if m:
        specs["storage"] = m.group(1)

    # Screen size — e.g. '15.6"' / "14 inch"
    m = re.search(r'(\d+(?:\.\d+)?)\s?["\'\- ]?(?:inch|\")', title, re.I)
    if m:
        specs["screen_size"] = m.group(1) + '"'

    # Processor — Intel Core iX / Ryzen X / Apple M
    m = re.search(
        r'(Intel\s?Core\s?i[3579][\-\s\w]*'
        r'|Ryzen\s?[3579][\-\s\w]*'
        r'|Apple\sM\d)',
        title, re.I
    )
    if m:
        specs["processor"] = m.group(1).strip()

    # GPU — RTX / GTX / RX / Intel UHD
    m = re.search(
        r'(RTX\s?\d{3,4}|GTX\s?\d{3,4}|RX\s?\d{3,4}|Intel\s?UHD)',
        title, re.I
    )
    if m:
        specs["gpu"] = m.group(1)

    return specs


print("✅ Helper functions defined")

✅ Helper functions defined

## Cell 4 — Scrape Noon
Scrapes up to **MAX_PAGES** pages from Noon Egypt's laptop category using **URL-based pagination** (`?page=N`).  
A seen-titles guard stops if the site repeats the same products.

In [4]:
# ── Settings ──────────────────────────────────────────────────────
NOON_BASE_URL = "https://www.noon.com/egypt-en/electronics-and-mobiles/computers-and-accessories/computers-new/laptops/"
MAX_PAGES     = 10          # Max pages to scrape (set to None for all pages)
# ──────────────────────────────────────────────────────────────────


def scrape_noon(base_url=NOON_BASE_URL, max_pages=MAX_PAGES):
    """
    Scrape laptop listings from Noon Egypt using URL-based pagination.

    Noon appends ?page=N to the base URL for pages > 1.
    Page 1  → https://…/laptops/
    Page 2  → https://…/laptops/?page=2
    Page N  → https://…/laptops/?page=N

    Parameters
    ----------
    base_url  : str  – Noon laptops category URL (no page param)
    max_pages : int  – Maximum number of pages (None = scrape until end)

    Returns
    -------
    pd.DataFrame with columns:
        name, price, rating, reviews_count, screen_size,
        processor, ram, storage, gpu, url, image, source
    """
    driver = get_driver()
    all_laptops = []
    seen_titles = set()          # duplicate guard per run

    for page in range(1, (max_pages or 9999) + 1):
        # Build page URL — page 1 uses the bare base URL
        page_url = base_url if page == 1 else f"{base_url}?page={page}"

        print(f"\n{'='*40}")
        print(f"  PAGE {page}  →  {page_url}")
        print(f"{'='*40}")

        driver.get(page_url)

        try:
            WebDriverWait(driver, 20).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, '[data-qa="plp-product-box"]'))
            )
        except Exception:
            print("⚠️  Timed-out waiting for products — stopping.")
            break

        time.sleep(2)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)

        cards = driver.find_elements(By.CSS_SELECTOR, '[data-qa="plp-product-box"]')
        print(f"Found {len(cards)} products")

        if not cards:
            print("⚠️  No products found — stopping.")
            break

        new_on_page = 0
        for idx, card in enumerate(cards):
            try:
                try:
                    title = card.find_element(By.CSS_SELECTOR, '[data-qa="plp-product-box-name"]').text.strip()
                except Exception:
                    title = None

                # Stop if we've already seen this product (page didn't advance)
                if title and title in seen_titles:
                    continue
                if title:
                    seen_titles.add(title)
                    new_on_page += 1

                try:
                    price = card.find_element(By.CSS_SELECTOR, '[data-qa="plp-product-box-price"] strong').text.strip()
                except Exception:
                    price = None

                try:
                    rating = card.find_element(
                        By.CSS_SELECTOR,
                        '.RatingPreviewStar-module-scss-module__zCpaOG__textCtr'
                    ).text.strip()
                except Exception:
                    rating = None

                try:
                    reviews = card.find_element(
                        By.CSS_SELECTOR,
                        '.RatingPreviewStar-module-scss-module__zCpaOG__countCtr span'
                    ).text.strip()
                except Exception:
                    reviews = None

                try:
                    image = card.find_element(By.CSS_SELECTOR, 'img[class*="productImage"]').get_attribute("src")
                except Exception:
                    image = None

                try:
                    product_url = card.find_element(By.CSS_SELECTOR, 'a').get_attribute("href")
                except Exception:
                    product_url = None

                specs = extract_specs(title)

                all_laptops.append({
                    "name":          title,
                    "price":         price,
                    "rating":        rating,
                    "reviews_count": reviews,
                    "screen_size":   specs["screen_size"],
                    "processor":     specs["processor"],
                    "ram":           specs["ram"],
                    "storage":       specs["storage"],
                    "gpu":           specs["gpu"],
                    "url":           product_url,
                    "image":         image,
                    "source":        "Noon",
                })

                short_title = (title[:65] + "...") if title and len(title) > 65 else (title or "Unknown")
                print(f"  {idx+1:>3}. {short_title}")

            except Exception as e:
                print(f"  ⚠️  Product {idx+1} error: {e}")

        # If zero new products came in, the site didn't advance → stop
        if new_on_page == 0:
            print("\n🏁 No new products on this page — scraping complete.")
            break

    driver.quit()

    df = pd.DataFrame(all_laptops)
    print(f"\n✅ Noon scraping done — {len(df)} products collected")
    return df


# ── Run ───────────────────────────────────────────────────────────
noon_df = scrape_noon()
noon_df.head()

========================================
  PAGE 1  →  https://www.noon.com/egypt-en/electronics-and-mobiles/computers-and-accessories/computers-new/laptops/
========================================
Found 50 products
    1. Apple MacBook Air MGN63 With 13 Inch Display, M1 Chip 8-Core CPU ...
    2. Apple MacBook Pro MDE34 | 14 Inch Display | Apple M5 Chip | 10-Co...
    3. Apple New 2024 MacBook Air MRXW3 13-inch Display, Apple M3 Chip 8...
    4. Apple MacBook Pro MDE04 | 14 Inch Display | Apple M5 Chip | 10-Co...
    5. Apple MacBook Pro MX2H3 Liquid XDR Retina 14-Inch Display, M4 Pro...
    6. Apple MacBook Air MW0W3 | 13 Inch Display | Apple M4 Chip | 10-Co...
    7. Lenovo LAPTOP LENOVO LOQ 15AHP10 AMD RYZEN 7 250 RAM 16G DDR5 560...
    8. ASUS FX608JMR-RV017W ASUS TUF Gaming F16 Laptop with 16 inch FHD ...
    9. Apple New 2026 MacBook Air MDHE4 | 13 Inch Display | Apple M5 Air...
   10. Apple MacBook Air MC6T4 | 13 Inch Display | Apple M4 Chip | 10-Co...
   11. Apple New 2026 MacBook Air MDVH4 | 15 Inch Display | Apple M5 Air...
   12. HP Victus 15‑fa1035NE Gaming Laptop – Intel Core i5‑13500H – 16GB...
   13. Apple New 2025 MacBook Air MW0Y3 13-Inch Display, Apple M4 Chip 1...
   14. Lenovo LAPTOP LENOVO LOQ ESSENTIAL 15IRX11 CPU I7 13650 HX RAM 16...
   15. Lenovo LOQ 15IAX9E Gaming Laptop, 15.6" FHD 144Hz IPS Display, In...
   16. DELL Vostro 3520 Laptop With 15.6-inch FHD (1920x1080) Display, C...
   17. Apple New 2025 MacBook Air MW123 13-Inch Display, Apple M4 Chip 1...
   18. Apple New 2026 MacBook Air MDHE4 13 Inch Display | M5 Air 10-Core...
   19. Lenovo LOQ 15IAX9E Core i5-12450HX 512GB SSD 16GB Ram Nvidia GeFo...
   20. Apple New 2025 MacBook Air MW1M3 15-Inch Display, Apple M4 Chip 1...
   21. Apple New 2025 MacBook Air MC6T4 13-Inch Display, Apple M4 Chip 1...
   22. Lenovo LAPTOP LENOVO LEGION 5 15IAX10 Intel Core Ultra 9 275HX RA...
   23. MSI LAPTOP MSI Katana 15 HX B14WEK Black Intel Core i7-14650HX RA...
   24. Apple New 2025 MacBook Air MW123 13-Inch Display, Apple M4 Chip 1...
   25. Lenovo Legion Pro 5 16IRX9 (Upgraded Version) Laptop With 16-Inch...
   26. Apple New 2026 MacBook Air MDHA4 13 Inch Display | M5 Air 10-Core...
   27. Lenovo (Upgraded Version) LOQ 15IAX9E Gaming (2025) Laptop With 1...
   28. Lenovo (Upgraded Version) LOQ 15ARP9 Gaming Laptop with LA1 AI Ch...
   29. DELL (Upgraded Version) Latitude 7420 Laptop With 14-Inch FHD Dis...
   30. Lenovo LOQ 15IRX9 Gaming Laptop, 15.6" FHD 144Hz IPS Display, Int...
   31. Apple New 2025 MacBook Air MC6U4 13-Inch Display, Apple M4 Chip 1...
   32. Lenovo IdeaPad 5 Laptop With 15.6-Inch Display, Core i5-1235U Pro...
   33. Apple New 2025 MacBook Air MW0Y3 13-Inch Display, Apple M4 Chip 1...
   34. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   35. Apple New 2025 MacBook Air MC7C4 15-Inch Display, Apple M4 Chip 1...
   36. Lenovo LOQ 15IRX9 Laptop With 15.6-Inch Display, Core i5-13450HX ...
   37. DELL (Upgraded Version) Vostro 3530 Laptop With 15.6-Inch Display...
   38. Apple New 2025 MacBook Air MC7A4 15-Inch Display, Apple M4 Chip 1...
   39. Apple New 2025 MacBook Air MW1L3 15-Inch Display, M4 chip 10-core...
   40. HP (Upgraded Version) Victus 15-fa2013dx Gaming Laptop, 15.6" FHD...
   41. HP NB Victus Gaming 16–R0045ne(81Q00EA)COR i7–13700H RA/ 2*8GB DD...
   42. Lenovo IdeaPad Slim 3 15IRH10 – Intel Core i5‑13420H – 16GB DDR5 ...
   43. DELL Latitude 3450 Laptop With 14 Inch Full HD (1920x1080) Displa...
   44. Apple MacBook Air MW0X3 With 13 Inch Display, M4 Chip 10-Core CPU...
   45. Asus Vivobook S 14 Flip TN3402YA-LZ005W Laptop, AMD Ryzen 5 7530U...
   46. ASUS TUF Gaming A16 FA608UH-RV007W Laptop with 16 Inch WUXGA / AM...
   47. HP VICTUS Laptop With 15.6-inch 144Hz Display, Core i7-13700H Pro...
   48. DELL Latitude 5450 Laptop With 14 Inch Full HD Display, Core i5-1...
   49. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   50. Lenovo LOQ 15IRX10 Gaming Laptop, 15.6" FHD IPS 144Hz Display, In...

========================================
  PAGE 2  →  https://www.noon.com/egypt-en/electronics-and-mobiles/computers-and-accessories/computers-new/laptops/?page=2
========================================
Found 65 products
    1. HP Renewed - EliteBook 840 G6 Laptop With 14 Inch Touch Screen Di...
    2. HP ProBook 450 G10 (Upgraded Version) Laptop With 15.6-Inch Displ...
    3. HP VCTUS 15 FA1036NE Laptop with 15.6 inch FHD / Intel Core i5-13...
    4. ASUS S3407CA-LY065W Vivobook S Laptop with 14 inch WUXGA / Core U...
    5. Lenovo Laptop Lenovo IdeaPad Slim 3 15IRH10, Intel Core i7‑13620H...
    7. HP VCTUS 15 FA1082wm Laptop with 15.6 inch FHD / Intel Core i5-13...
    8. HP Renewed - EliteBook 840 G6 Laptop With 14 Inch FHD Display,Int...
    9. DELL 2024 Inspiron 3530 Think & Laptop With 15.6-Inch Full HD (19...
   10. HP Elitebook 850 G7 Laptop With 15.6-Inch Display, Core i5-10210U...
   11. DELL Latitude 7400 Laptop With 14-Inch Full HD Display, Core i5 P...
   12. Apple MacBook Pro MX2X3 With 16.2 Inch Display, M4 Pro Chip 14-Co...
   13. Apple New 2026 MacBook Air MDHH4 | 13 Inch Display | Apple M5 Air...
   14. HP Victus 15-fa2013DX Laptop with 15.6 inch FHD / Intel Core i5-1...
   15. HP Victus 16 Laptop With 16.1-Inch Full HD(1920x1080) 144Hz Displ...
   16. HP EliteBook 845 G8 | AMD Ryzen 5 Pro | 14" inch | RAM 16GB | Har...
   17. ASUS TUِF Gaming A15 FA506NCQ-HN167W - AMD Ryzen 7 170 - NVIDIA G...
   18. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   19. HP (Upgraded Version) Victus 15-FA1082WM Gaming Laptop With 15.6-...
   20. MSI Katana 15 HX-B14WGK Laptop - Intel® Core™ i7-14700HX - 16GB -...
   21. ASUS Vivobook S14 Flip TP3402VA-LZ065W -90NB10W2-M00ST0 - i5-1342...
   22. Apple New 2025 MacBook Air MW0W3 13-Inch Display, Apple M4 Chip 1...
   23. HP 15-Fa1003Ne Victus Gaming Laptop With 15.6 Inch FHD / Core I7-...
   24. HP (Upgraded Version) 2024 Newest ProBook 460 G11 Laptop With 16-...
   25. HP 2024 Newest ProBook 460 G11 (Upgraded Version) Laptop With 16-...
   26. DELL Latitude 5590 Laptop With 15.6-Inch Display, Core i7 Process...
   27. HP Victus 15-fb3093dx Laptop With 15.6-Inch FHD IPS 144Hz Display...
   28. Apple New 2025 MacBook Air MW103 13-Inch Display, Apple M4 Chip 1...
   29. ASUS Vivobook 16 X1605VA-OLED507W X1605VA-OLED507W Laptop with 16...
   30. HP Laptop 14-em0003ne: Ryzen 7-7730U, 16GB RAM, 512GB SSD, AMD Ra...
   31. Lenovo LOQ Essential 15IRX11 Gaming Laptop With 15.6 Inch Full HD...
   32. Lenovo LOQ 83LK00C9US Laptop, 15.6" FHD IPS Display, Intel Core i...
   33. Lenovo IdeaPad 5 14IRH9 2-in-1 Convertible (2024) Laptop – 13th G...
   34. DELL Latitude 7290 Laptop With 12.5-Inch Display, Core i7 Process...
   35. HP ProBook 460 G11 Laptop With 16-inch Display, Intel Core Ultra ...
   36. Lenovo IdeaPad Slim 3 Laptop 15IRH8, Intel Core i5-13420H, 16GB D...
   37. Apple New 2026 MacBook Air MDHA4 | 13 Inch Display | Apple M5 Air...
   38. Lenovo IdeaPad 5 2-in-1 14IRH9 | Intel® UHD Graphics | Intel 13th...
   39. HP 15-fa2787nr Victus Gaming Laptop, 15.6" FHD IPS 144Hz Display,...
   42. HP ProBook 640 G4 Notebook With 14-Inch Display, Core i7 Processo...
   44. Apple New 2025 MacBook Air MW1H3 15-Inch Display, Apple M4 Chip 1...
   45. Lenovo LOQ Gaming Laptop With 15.6 Inch Full HD (1920x1080) IPS D...
   46. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   47. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   48. Lenovo Yoga 7 2-In-1 Touchscreen Laptop with 14-Inch Display, AMD...
   49. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   50. Lenovo (Upgraded Version) LOQ 15IRX9 Gaming laptop With 15.6-Inch...
   51. Lenovo (Upgraded Version) LENOVO LOQ 15IRX9 – Model: 83DV012HED I...
   52. DELL Vostro 3515 Laptop With 15.6-inch Full HD Display, Ryzen 3 3...
   53. Apple New 2026 MacBook Air MDHH4 13 Inch Display | M5 Air 10-Core...
   54. HP 15-fd0021nx Laptop With 15.6 Inch Full HD Display, Intel Core ...
   55. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   56. MSI Raider 18 HX A2XWJG Laptop – Intel® Core™ Ultra 9 285HX – RAM...
   57. ASUS (Upgraded Version) TUF A16 FA608PM Gaming Laptop With 16-Inc...
   58. Apple MacBook Air MW1J3 | 15 Inch Display | Apple M4 Chip | 10-Co...
   59. Apple New 2026 MacBook Air MDH74 13 Inch Display | M5 Air 10-Core...
   60. HP (Upgraded Version) Envy x360 Convertible 2-In-1 Laptop With 15...
   61. Apple MacBook Pro MW2U3 | 14.2 Inch Display | Apple M4 Chip | 10-...
   62. HP EliteBook 840 G8 Laptop With 14-Inch Display, Core i7-1165G7 P...
   63. MSI Katana 15 HX B14WFK (Black) Gaming Laptop, 15.6" QHD IPS 165H...
   64. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   65. Lenovo LOQ 15IAX9 Gaming Laptop with LA1 Ai Chip | NVIDIA GeForce...

========================================
  PAGE 3  →  https://www.noon.com/egypt-en/electronics-and-mobiles/computers-and-accessories/computers-new/laptops/?page=3
========================================
Found 65 products
    4. ASUS (Upgraded Version) ASUS TUF Gaming FX607V Laptop With 16-inc...
    5. Lenovo IdeaPad Slim 3 15IRH8 Laptop, 15.6" FHD IPS Display, Intel...
    9. ASUS TUF F16 Gaming Laptop With 16 Inch Full HD (1920x1080) Displ...
   10. HP Victus 15-FA1038NE Gaming Laptop Intel Core I7-13700H 512GB SS...
   11. Lenovo IdeaPad 3 14IML05 Laptop With 14-Inch FHD (1920x1080) Disp...
   12. Honor MagicBook Art 14 Laptop With 14.6-Inch Full HD (3120x2080) ...
   13. Lenovo LOQ 15IAX9 Gaming Laptop With 15.6-Inch Full HD (1920x1080...
   16. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   17. HP (Upgraded Version) Pavilion x360 2 in 1 Laptop With 14-Inch Di...
   18. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   20. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   21. ASUS VivoBook 16 OLED Laptop X1605VA-OLED507W, 16.0 inch WUXGA Di...
   22. Apple New 2025 MacBook Air MW133 13-Inch Display, Apple M4 Chip 1...
   26. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   28. GIGABYTE Gaming A16 CVH (Upgraded Version) Laptop With 16 Inch WU...
   29. Lenovo (Upgraded Version) Lenovo Legion Pro 7 16IAX10H Gaming Lap...
   31. ASUS (Upgraded Version) TUF Gaming F16 FX608JMR 16" FHD+ 165Hz Ga...
   32. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   33. ASUS (Upgraded Version) Notebook ASUS TUF Gaming F16 FX607VU- RL0...
   34. Lenovo LOQ 15IRX9 Gaming Laptop Intel Ci7-13650HX 16GB RAM 512GB ...
   36. ASUS (Upgraded Version) TUF Gaming F16 FX608JMR 16" WUXGA Display...
   37. MSI LAPTOP MSI Cyborg 15 A2RUDX CPU Core 7 240H RAM16G DDR5 8GB*2...
   38. Lenovo Ideapad Slim 3 (Upgraded Version) Laptop With 15.6-Inch Fu...
   39. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   40. Apple New 2024 MacBook Air MRXQ313-inch Display, Apple M3 Chip 8-...
   41. Lenovo LAPTOP LENOVO IdeaPad Slim 3 15AMN8 AMD Ryzen 5 7520U RAM ...
   42. Apple MacBook Pro MDE14 | 14 Inch Display | Apple M5 Chip | 10-Co...
   44. MSI Prestige 13 AI Evo A1MG Laptop, Intel Core Ultra 7-155H Proce...
   45. Acer Aspire 5 A515 Laptop With 15.6 Inch Full HD (1920x1080) Disp...
   46. Apple MacBook Pro MW2V3 Liquid XDR Retina 14-Inch Display, M4 Chi...
   47. Lenovo (Upgraded Version) LOQ 15IAX9E Gaming Laptop, 15.6" FHD IP...
   48. ASUS (Upgraded Version) TUF A14 Gaming Laptop With 14-Inch Displa...
   49. ASUS FX607VU-RL165W ASUS TUF Gaming F16 Laptop with 16 inch FHD /...
   50. Lenovo Laptop Gaming Lenovo LOQ 15IRX9, Intel Core i5‑13450HX, 16...
   51. ASUS Vivobook Go 15 E1504FA-BQ8233W AMD Ryzen 3 30 256GB SSD 8GB ...
   52. ASUS X1407QA-LY045W Vivobook Laptop with 14-Inch WUXGA Display,Sn...
   53. Apple New 2026 MacBook Pro MGEA4 | 16.2 Inch Display | Apple M5 P...
   54. ASUS Vivobook S 14 Flip 2-in-1 Convertible (2023) Laptop With 14-...
   55. HP Probook X360 11-G3 2-In-1 Laptop With 11.6-Inch Display, Celer...
   56. ASUS Vivobook 15 X1504VA-BL823W Laptop With 15.6-Inch Display, In...
   57. MSI Crosshair 16 HX AI D2XWFKG Laptop With 16-Inch QHD+, Intel Co...
   58. Lenovo LOQ 15IRX9 Gaming Laptop With 15.6-inch Full HD(1920x1080)...
   59. Lenovo (Upgraded Version) LOQ 15IRX9 Gaming Laptop With 15.6 Inch...
   60. ASUS TUF Gaming A14 FA401UU-RG028W Gaming Laptop AMD R7 8845HS, 1...
   62. ASUS FA608UH-RV007W ASUS TUF Gaming A16 Laptop with 16 inch FHD /...
   65. Lenovo (Upgraded Version) Legion 5 16IRX9 Gaming Laptop With 16-I...

========================================
  PAGE 4  →  https://www.noon.com/egypt-en/electronics-and-mobiles/computers-and-accessories/computers-new/laptops/?page=4
========================================
Found 65 products
    4. HP (Upgraded Version) Envy X360 14-es1023dx Touchscreen Laptop Wi...
    5. HP (Upgraded Version) OmniBook 5 Flip Personal Laptop With 14-Inc...
    9. ASUS ROG Strix G16 G614PH-RV161W Laptop with 16 Inch WUXGA / AMD ...
   10. Apple MacBook Neo | 13-Inch Display | A18 Pro, 6-core CPU, 5-core...
   11. ASUS VivoBook 16 Laptop X1607CA-UL005W, 16.0 inch WUXGA Display, ...
   12. ASUS Vivobook S14 S3407QA-SF067W - 90NB16B1‑M003T0 -Snapdragon X ...
   13. Lenovo Legion 5 Gaming Laptop – Intel Core i7-14650HX – 16 Cores ...
   16. Lenovo LEGION 5 16IAX10 Laptop With 16-Inch WQXGA Display,Core Ul...
   17. Lenovo IDEAPAD 5 2 IN 1 -83DT008YED-Intel Core 7 150U -16GB Solde...
   18. Apple New 2025 MacBook Air MW0X3 13-Inch Display, Apple M4 Chip 1...
   20. Apple MacBook Pro MDE64 | 14 Inch Display | Apple M5 Chip | 10-Co...
   21. Apple MacBook Pro MW2U3 | 14.2 Inch Display | Apple M4 Chip | 10-...
   22. HP OmniBook 5 Flip 14 FP0050NE / Intel Core i5‑120U / 8GB LPDDR5 ...
   26. HP ProBook 450 G9 - Intel® Core™ i7-1255U - 8GB - 512GB SSD - NVI...
   28. Apple MacBook Pro MDE34 | 14 Inch Display | Apple M5 Chip | 10-Co...
   29. ASUS ROG Strix G615 (2025) Gaming Laptop With 16 Inch WUXGA (1920...
   30. MSI VICTOR 16 HX AI A2XWHG Core Ultra 7 RTX 5070 TI 12GB 16GB RAM...
   31. Hp Victus Gaming 15-fa1039ne Intel® Core™ i7-13700H 8GB Ram , 512...
   32. HP Envy 14-ES1013DX Laptop With 14-Inch Display, Core Ultra 5-120...
   33. ASUS (Upgraded Version) ROG Strix 16 Gaming Laptop, 16" WUXGA 165...
   34. ASUS (Upgraded Version) TP3402VA-LZ065W Vivobook Flip Laptop with...
   36. Lenovo ThinkPad E16 Gen 1 Laptop With 16-inch (1920x1200) Display...
   37. DELL Alienware 16 Aurora Laptop With 16 Inch QHD (2560x1600) Disp...
   38. HP 15S-Eq2009Ne Laptop With 15.6 Inch FHD /Ryzen 7 5700U /8 GB Ra...
   39. Lenovo Legion 5 15IRX10 Gaming Laptop, 15.1" WQXGA OLED 165Hz Dis...
   40. Lenovo (Upgraded Version) Lenovo LOQ 15IRH8 Laptop With 15.6 inch...
   42. Apple MacBook Pro MCX04 Liquid XDR Retina 14-Inch Display, M4 Chi...
   44. DELL Alienware 16 Aurora Laptop With 16 Inch QHD Display 120Hz, C...
   45. ASUS G614FM-RV169W ROG Strix G16 Laptop with 16 inch FHD / AMD Ry...
   46. Lenovo (Upgraded Version) Legion 5 16IRX9 Laptop With 16 Inch Ful...
   47. Lenovo (Upgraded Version) IdeaPad Slim 3 Laptop With 15-Inch Disp...
   48. MSI Crosshair 16 HX AI D2XWGKG Gaming Laptop, Intel Core Ultra 7 ...
   49. LENOVO LOQ 15 15IRX9 83DV008QED Intel i7-13650HX 14-Cores, RTX 30...
   50. HP Victus 15-fa1023 nia Laptop with 15.6 inch FHD / Intel Core i5...
   51. Lenovo (Upgraded Version) LOQ 15IRX9 15.6-Inch Display, Core i7-1...
   52. HP Victus 16-R1052NE Gaming Laptop Intel Core i7-14700HX 1TB SSD ...
   53. ASUS Vivobook 16 X1605VA-OACH007W X1605VA-OACH007W Laptop with 16...
   54. Lenovo Legion 5 15IRX10 Gaming (2025) Laptop With 15.1-Inch Displ...
   55. Lenovo LOQ 15IRX9 Gaming Laptop, 15.6" FHD IPS 144Hz G-SYNC Displ...
   56. MSI Cyborg 15 A13VE Gaming Laptop With 15.6 Inch Full HD (1920x10...
   57. ASUS G614PR-RV161W ROG Strix G16 Laptop with 16 inch FHD / AMD Ry...
   58. DELL Lenovo ThinkPad E14 Gen 6 | Core Ultra 7‑155H | 16GB DDR5 | ...
   59. Apple New 2024 MacBook Air 15-inch (2880x1864) Display, Apple M3 ...
   60. ASUS TUF Gaming F16 FX607VJB-RL165W Gaming Laptop With 16-Inch FH...
   61. Lenovo LAPTOP LENOVO Legion 5 15IAX10 CPU Ultra 7 255HX RAM 32 G ...
   62. Lenovo IdeaPad Slim 3 Laptop 15IRH10, Intel Core i5-13420H, 16GB ...
   63. ASUS Zenbook S16 UM5606WA | AI PC AI laptop -AMD Ryzen™ AI 9 HX 3...
   64. Asus ProArt P16 H7606WI-ME139W Ryzen™AI 9-HX370 , 64GBRAM , 2T SS...
   65. Lenovo (Upgraded Version) LOQ Gaming Laptop, Intel Core i7-13620H...

========================================
  PAGE 5  →  https://www.noon.com/egypt-en/electronics-and-mobiles/computers-and-accessories/computers-new/laptops/?page=5
========================================
Found 65 products
    4. ASUS ROG Strix Scar 18 Gaming Laptop With 18-inch 2.5K Display 24...
    5. Lenovo ThinkPad E14 Gen 6 Business Laptop | Core Ultra 7 155H | 1...
    9. Lenovo IdeaPad 5 Laptop With 15.6 Inch FHD/ Core I5-1235U /16 GB ...
   10. DELL Latitude 5520 Laptop With 15.6 Inch HD Display, Core i5-1135...
   11. Lenovo IdeaPad 330 Laptop With 15.6-Inch Display, Intel Core i7 P...
   12. HP Laptop AI 15-fd2001ne (C53H7EA)Core™ Ultra 7 processor with In...
   13. Lenovo LOQ 15IAX9E Gaming Laptop – Intel Core i5‑12450HX – Octa C...
   16. HP "Hp Victus 15-fa1097ne Gaming - 13th Intel i7-13700H 14-Cores,...
   17. HP Laptop HP ProBook 460 G11, Intel Core Ultra 7 155U, 16-inch, 8...
   18. MSI Cyborg 15 A13VE i7-13620H 16GB DDR5 512GB NVMe RTX 4050 IPS F...
   20. DELL Latitude 5550 Laptop With 15.6 Inch Full HD Display,Core i5-...
   21. DELL (Upgraded Version) Vostro 3530 Laptop With 15.6 Inch Full HD...
   22. Lenovo (Upgraded Version) Lenovo LOQ 15IRX9 Gaming Laptop with LA...
   26. DELL Latitude 5520 (Upgraded Version) Laptop With 15.6-Inch Displ...
   28. ASUS ROG Flow Z13 Gaming (2025) Laptop – AMD Ryzen AI MAX+ 395 13...
   29. Lenovo LOQ Gaming Laptop With 15.6 Inch Full HD(1920X1080) Displa...
   30. Lenovo IdeaPad Slim 3 15IRH8 (Upgraded Version) Laptop With 15.6-...
   31. Dell Latitude 3550 Laptop – 15.6" FHD - Intel Core i5‑1335U - 8GB...
   32. HP VCTUS 15 FA1018NIA Laptop with 15.6 inch FHD / Intel Core i5-1...
   33. Lenovo ThinkPad E15 Laptop With 15.6-Inch Display, Core i5 1135G7...
   34. Lenovo Ideapad Gaming 3 15Ach6 Laptop with - 15.6 inch display Am...
   36. DELL Inspiron 7573 Convertible 2-In-1 Laptop With 15.6-Inch Displ...
   37. HP NB Victus Gaming 16–R1049 CORI7 14700HX /16G/1TBSSD/RTX4060/16...
   38. HP Victus 15-fa1043ne Gaming Laptop - 13th Intel i5-13500H 12-Cor...
   39. Lenovo Thinkbook 15 G2 ITL Laptop With 15.6 Inch Full HD Display,...
   40. ASUS G615LW-RV132W ROG Strix G16 Laptop with 16 inch FHD / Ultra ...
   41. Lenovo LOQ Gaming Laptop 15.6" - Core i5‑13450HX - 24GB RAM - 512...
   42. Dell Latitude 3420 - IntelÂ® Coreâ„¢ i5-1135G7 - 8GB - 256GB SSD ...
   44. Msi Katana A15 AI B8VF Gaming Laptop AMD Ryzen 9 8945HS 512GB NVM...
   45. DELL (Upgraded Version) Inspiron 7440 2-In-1 Laptop With 14-Inch ...
   46. Lenovo Ideapad 5 14IRH9 Laptop – Intel Core i7-13620H, 16GB RAM, ...
   47. MSI Vector 16 HX AI A2XWHG - 9S7-15M352-070 Laptop , Intel Core U...
   48. HP VICTUS 16- R1052 Laptop with 16 inch FHD / Intel Core i7-14700...
   49. HP OmniBook 3 AI Laptop 15.6" Ryzen AI 5 / 16GB / 512GB SSD / Rad...
   50. Apple 2023 Newest MacBook Pro MUW73 Laptop M3 Max chip with 16‑co...
   51. DELL Latitude 3550 Laptop With 15.6-Inch Display, Intel Core i5-1...
   52. HP ProBook 460 G11 Laptop With 16-Inch WUXGA(1920X1200) Display, ...
   53. HP 15s-eq2009ne Laptop With 15.6-inch Display Ryzen 7 5700U Proce...
   54. Apple MacBook Pro MDE44 With 14 Inch Display, M5 Chip 10-Core CPU...
   55. Lenovo (Upgraded Version) ThinkPad E16 Gen 3 Business Laptop, 16"...
   56. Lenovo Legion Pro 5 Laptop With 16-Inch Full HD Display, Core Ult...
   57. ASUS S3607CA-SH070W Vivobook S Laptop with 16 inch OLED / Core Ul...

,name,price,rating,reviews_count,screen_size,processor,ram,storage,gpu,url,image,source
0,"Apple MacBook Air MGN63 With 13 Inch Display, ...","39,333",4.6,5.6K,"13""",None,8GB,256GB SSD,None,https://www.noon.com/egypt-en/macbook-air-mgn6...,https://f.nooncdn.com/p/pzsku/Z073CC3975B50405...,Noon
1,Apple MacBook Pro MDE34 | 14 Inch Display | Ap...,"114,944",4.5,666,"14""",Apple M5,24GB,1TB SSD,None,https://www.noon.com/egypt-en/macbook-pro-mde3...,https://f.nooncdn.com/p/pzsku/ZB86807EF11E0C21...,Noon
2,Apple New 2024 MacBook Air MRXW3 13-inch Displ...,"51,999",4.6,724,"13""",Apple M3,8GB,512GB SSD,Intel UHD,https://www.noon.com/egypt-en/new-2024-macbook...,https://f.nooncdn.com/p/pzsku/ZAAE18FC6CBA31C4...,Noon
3,Apple MacBook Pro MDE04 | 14 Inch Display | Ap...,"97,433",4.5,666,"14""",Apple M5,16GB,512GB SSD,None,https://www.noon.com/egypt-en/macbook-pro-mde0...,https://f.nooncdn.com/p/pzsku/Z2276A3E16D90EAC...,Noon
4,Apple MacBook Pro MX2H3 Liquid XDR Retina 14-I...,"119,508",4.5,666,"14""",None,24GB,512GB SSD,None,https://www.noon.com/egypt-en/macbook-pro-mx2h...,https://f.nooncdn.com/p/pzsku/ZDC348E47B0C87C4...,Noon

## Cell 5 — Scrape Amazon Egypt
Scrapes up to **MAX_PAGES** pages from the Amazon Egypt laptop search results using **URL-based pagination** (`&page=N`).  
A seen-ASINs guard stops if Amazon repeats results.

In [5]:
# ── Settings ──────────────────────────────────────────────────────
AMAZON_BASE_URL = "https://www.amazon.eg/s?k=laptops&i=electronics"
MAX_PAGES       = 10          # Max pages to scrape (set to None for all pages)
# ──────────────────────────────────────────────────────────────────


def scrape_amazon(base_url=AMAZON_BASE_URL, max_pages=MAX_PAGES):
    """
    Scrape laptop listings from Amazon Egypt using URL-based pagination.

    Amazon appends &page=N to the search URL.
    Page 1  → https://…?k=laptops&i=electronics
    Page 2  → https://…?k=laptops&i=electronics&page=2
    Page N  → https://…?k=laptops&i=electronics&page=N

    Parameters
    ----------
    base_url  : str  – Amazon search URL (no page param)
    max_pages : int  – Maximum number of pages (None = scrape until end)

    Returns
    -------
    pd.DataFrame with columns:
        name, price, rating, reviews_count, screen_size,
        processor, ram, storage, gpu, url, image, source
    """
    driver = get_driver()
    all_laptops = []
    seen_asins  = set()          # duplicate guard per run

    for page in range(1, (max_pages or 9999) + 1):
        page_url = base_url if page == 1 else f"{base_url}&page={page}"

        print(f"\n{'='*40}")
        print(f"  PAGE {page}  →  {page_url}")
        print(f"{'='*40}")

        driver.get(page_url)

        try:
            WebDriverWait(driver, 20).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, 'div[data-component-type="s-search-result"]'))
            )
        except Exception:
            print("⚠️  Timed-out waiting for products — stopping.")
            break

        time.sleep(3)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)

        products = driver.find_elements(By.CSS_SELECTOR, 'div[data-component-type="s-search-result"]')
        print(f"Found {len(products)} products")

        if not products:
            print("⚠️  No products found — stopping.")
            break

        new_on_page = 0
        for idx, product in enumerate(products):
            try:
                asin = product.get_attribute("data-asin")
                if not asin:          # sponsored card with no ASIN
                    continue
                if asin in seen_asins:
                    continue
                seen_asins.add(asin)
                new_on_page += 1

                try:
                    title = product.find_element(By.CSS_SELECTOR, 'h2 span').text.strip()
                except Exception:
                    title = None

                try:
                    whole    = product.find_element(By.CSS_SELECTOR, '.a-price-whole').text.strip()
                    fraction = product.find_element(By.CSS_SELECTOR, '.a-price-fraction').text.strip()
                    price    = whole + "." + fraction
                except Exception:
                    price = None

                try:
                    raw_rating = product.find_element(By.CSS_SELECTOR, '.a-icon-alt').get_attribute("innerHTML")
                    rating = raw_rating.split(" ")[0]
                except Exception:
                    rating = None

                try:
                    reviews = product.find_element(By.CSS_SELECTOR, '.a-size-base.s-underline-text').text.strip()
                except Exception:
                    reviews = None

                try:
                    image = product.find_element(By.CSS_SELECTOR, 'img.s-image').get_attribute("src")
                except Exception:
                    image = None

                try:
                    product_url = product.find_element(By.CSS_SELECTOR, 'a.a-link-normal.s-line-clamp-4').get_attribute("href")
                except Exception:
                    product_url = None

                specs = extract_specs(title)

                all_laptops.append({
                    "name":          title,
                    "price":         price,
                    "rating":        rating,
                    "reviews_count": reviews,
                    "screen_size":   specs["screen_size"],
                    "processor":     specs["processor"],
                    "ram":           specs["ram"],
                    "storage":       specs["storage"],
                    "gpu":           specs["gpu"],
                    "url":           product_url,
                    "image":         image,
                    "source":        "Amazon",
                })

                short_title = (title[:65] + "...") if title and len(title) > 65 else (title or "Unknown")
                print(f"  {idx+1:>3}. {short_title}")

            except Exception as e:
                print(f"  ⚠️  Product {idx+1} error: {e}")

        # No new ASINs → Amazon didn't advance (last page repeated)
        if new_on_page == 0:
            print("\n🏁 No new products on this page — scraping complete.")
            break

    driver.quit()

    df = pd.DataFrame(all_laptops)
    print(f"\n✅ Amazon scraping done — {len(df)} products collected")
    return df


# ── Run ───────────────────────────────────────────────────────────
amazon_df = scrape_amazon()
amazon_df.head()

========================================
  PAGE 1  →  https://www.amazon.eg/s?k=laptops&i=electronics
========================================
Found 27 products
    1. Lenovo LOQ 15IRX9 Gaming Laptop - 13th Intel Core i7-13650HX 14 C...
    2. Lenovo LOQ 15IRX10 Gaming Laptop, Intel Core i7-14700HX, 16GB RAM...
    3. MSI Katana 15 HX B14WFK (NVIDIA® GeForce RTX™ 5060 Laptop GPU, GD...
    4. HP Laptop 14-em0025ne: Ryzen 5-7520U, 8GB Ram, 512GB-SSD, AMD Rad...
    5. ASUS Vivobook 14 [X1405VA-H005W] i5-13420H / 8GB DDR4 / 512GB SSD...
    6. ASUS Vivobook 16 [X1605VA-ACH007W] Core™ i7-13620H /16GB DDR5 /51...
    7. Lenovo Ideapad Slim 3 15IRH10 Laptop Intel Core i5 13420H, 16GB R...
    8. HP OmniBook 3 AI PC15-fn0001ne: Ryzen AI 5 330, 16GB, 512GB-SSD, ...
    9. ASUS TUF F16 [FX607VJB-RL165W] Intel Core 5-210H /16GB DDR5 /512G...
   10. Dell Latitude 5310 2 in 1 Laptop Touch Screen 13.3" FHD (1920 x 1...
   11. Dell Latitude 5300 Touchscreen Laptop with Backlit Keyboard, 13.3...
   12. Dell Latitude 5310 2-in-1 Touchscreen Business Laptop, 13.3" FHD ...
   13. HP Laptop AI 15-fd2001ne Ultra 7-255U, 16GB Ram, 1TB SSD, Intel G...
   14. ASUS Vivobook 16 [X1605VA-OACH007W] Core™ i7-13620H /16GB DDR5 /5...
   15. HP OmniBook 5 Flip 2-in-1 Laptop,14-fp0050ne, Intel Core 5 120U, ...
   16. Dell Latitude 5410 14" FHD Business Laptop, Intel Core i5-10310U,...
   17. ASUS Vivobook 16 [X1607CA-UL005W] Core™ U5-225H /16GB DDR5 /512GB...
   18. Lenovo LOQ 15AHP10 Gaming Laptop,AMD Ryzen™ 7 250, 16GB RAM, 512G...
   19. Latitude Dell 5410 14" FHD Business Laptop, Core i5-10310U, 16GB ...
   20. Lenovo LOQ 15ARP9 Gaming Laptop AMD R5 7235HS, 16GB RAM, 512GB SS...
   21. Lenovo IdeaPad 5 2-in-1 14IRH9 Core i5-13420H, 16GB RAM, 512GB SS...
   22. Lenovo IdeaPad Slim 3 15IRH10 Intel Core i5-13420H, 16GB DDR5, 51...
   23. Dell Latitude 13 5300 2-in-1 8th Gen. Core i7 Ram 16 GB SSD 256GB...
   24. Lenovo Ideapad Slim 3 15IRH10 Laptop Intel Core i5 13420H 16GB RA...
   25. Lenovo Legion 5 15IRX10 Gaming Laptop Intel Core i7-13650HX, 16GB...
   26. HP Laptop 14-em0003ne: Ryzen 7-7730U, 16GB RAM, 512GB SSD, AMD Ra...
   27. Lenovo LOQ 15IAX9 Gaming Laptop, Intel Core i5 12600HX, 16GB RAM ...

========================================
  PAGE 2  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=2
========================================
Found 27 products
    4. ASUS Zenbook 14 [UX3405CA-PZ007W] Core™ U7-255H /16GB DDR5 /1TB S...
    5. HP EliteBook 840 G4 Business Laptop - Intel Core i5-7300U, 8GB, 2...
    6. Lenovo IdeaPad Slim 3 15IRH10: Core i7-13620H, 8GB, 512GB SSD, In...
    7. Apple 2026 MacBook Neo 13-inch Laptop with A18 Pro chip: Built fo...
    8. Dell Latitude 5420 Business Laptop, 14" FHD Display (1920 x 1080)...
    9. Lenovo LOQ 15IRX9 Gaming Laptop - 13th Intel Core i7-13650HX, 16G...
   10. Apple 2024 MacBook Pro Laptop with M4 Max, 14‑core CPU, 32‑core G...
   11. ASUS TUF F16 [FX608JHR-RV057W] Intel i7-14650HX /16GB DDR5 /512GB...
   12. Dell Latitude E 5550 Laptop with Intel Core i5 5th Gen and 4 GB R...
   13. ASUS Zenbook Duo|Intel Core Ultra 7 Processor 255H|32GB LPDDR5X|1...
   14. HP Laptop AI PC 15-fd2000ne Intel Core Ultra 5 225U (12-Core, 12 ...
   15. HP OmniBook 5 Flip14-fp0025ne i5-1334U, 8GB RAM, 512GB SSD, Intel...
   16. ASUS Vivobook S14 OLED M5606KA-RI417W – AMD Ryzen™ AI 7 350 – 24G...
   17. Lenovo LOQ 15IRX9 Gaming Laptop - 13th Intel Core i7-13650HX 14 C...
   19. Dell Latitude 5300 2-in-1 Laptop, Touchscreen, 13.3" FHD (1920 x ...
   20. HP 15-dw3023ne (2 GB GDDR5 Dedicated)-Display 15.6 FHD-OS Windows...
   22. GIGABYTE GAMING A16 CWH Gaming Notebook, 16" 165Hz FullHD 16:10 I...
   23. Lenovo LOQ 15IRX10 Gaming Laptop, Intel Core i7-13700HX, 16GB RAM...
   24. Lenovo Ideapad Slim 3 15IRH10 Laptop Intel Core i5 13420H, 16GB R...
   25. Lenovo IdeaPad Flex 5 2n1 convertible Laptop -Intel Core i5-1235U...
   26. Lenovo LOQ 15IRX10 Gaming Laptop, Intel Core i7-14700HX, 16GB RAM...
   27. Dell Vostro 3515 Laptop, AMD Ryzen 7-3700U, 15.6'' FHD, 512GB SSD...

========================================
  PAGE 3  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=3
========================================
Found 27 products
    4. Dell Latitude 5310 2-in-1 Touchscreen Business Laptop, 13.3 Inch ...
    5. ASUS Vivobook S16 [S3607CA-SH070W] Core™ U7-255H /16GB DDR5 /1TB ...
    7. MSI Modern B4MW Laptop, AMD R5-4500U, 8GB Ram, 256GB Ssd, Radeon ...
    8. ASUS TUF Gaming [FA401KH-RG019W] AMD Ryzen™ AI 7 350 / LPDDR5X 16...
    9. Apple 2025 MacBook Air 13-inch Laptop with M4 chip: Built for App...
   10. Apple 2025 MacBook Air 13-inch Laptop with M4 chip: Built for App...
   11. Lenovo LOQ 15IAX9 Gaming Laptop, Intel Core i5 13450HX, 16GB RAM ...
   12. HP ProBook 460 G11 Business Laptop 16” FHD+ Display, Intel Core U...
   13. ASUS Vivobook 16 [X1607QA-MB054W] Snapdragon® X X1 26 100 /16GB D...
   14. HP Victus Gaming 15-fb0034ne Laptop - Ryzen 7-5800H 8-Cores, 16 G...
   15. Apple 2022 MacBook Air Laptop with M2 Chip, 13.6in Liquid Retina ...
   16. Lenovo Legion 5 15IAX10 Gaming Laptop, Intel Core Ultra 9 275HX, ...
   17. Delll Latittude E6430 Laptop – Intell core i7-3520M, 8GB RAM, 500...
   18. Dell Latitude 5410 Business Laptop, 14'' FHD Notebook, 10th Gen I...
   19. HP ProBook G11 Laptop Notebook, Intel® Core™ Ultra 7 155H, 16 Cor...
   20. HP OMEN MAX 16-ak0007ne Gaming Laptop, AMD Ryzen AI 7 350, 16GB D...
   21. acer 2023 Flagship Chromebook 14" FHD 1080p IPS Touchscreen Light...
   22. Lenovo V15 Laptop - Intel Core i3-10110U, 4GB RAM, 1TB HDD, Integ...
   23. Dell Vostro 3530 Laptop (2023) | 15.6" 1920x1080 FHD | Core i7-13...
   24. Dell Vostro 3530 N1601PVNB3530U10 i7-1355U 32GB 512SSD 15.6 FullH...
   25. CHUWI 15.6" Laptop, 256GB LPDDR5 8GB SSD, Intel N100 (Beats N5095...
   26. Dell Vostro 3530 N3404PVNB3530U03 i5-1334U 32GB 512SSD 15.6 FHD F...
   27. Dell Vostro 3520 Laptop - 12th Intel Core i5-1235U 10-Cores, 8GB ...

========================================
  PAGE 4  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=4
========================================
Found 27 products
    4. acer Chromebook Spin 2-in-1 Convertible Laptop (2023), 8-Core Med...
    5. Adjustable Laptop Stand, Portable Aluminum Laptop Riser Laptop Ho...
    6. Laptop Stand, Laptop Holder Riser Computer Stand, Adjustable Alum...
    7. Adjustable laptop stand, portable aluminium laptop riser laptop h...
    8. SKY-TOUCH Laptop Stand for Desk, Adjustable Laptop Riser ABS+Sili...
    9. Sounce LCD Screen Cleaning 3 in 1 Screen Cleaner with Spray Cloth...
   10. ivoler Ergonomic Foldable Portable Adjustable Aluminum Laptop Com...
   11. Babacom Laptop Stand, 9 Levels Aluminium Laptop Stand, Portable, ...
   12. BUYIFY Folding Lap Desk, 23.6 Inch Portable Wood Black Laptop Bed...
   13. SupCares Laptop Stand, 7 Angles Adjustable Laptop Stand for Desk,...
   14. Astory Laptop Bed Tray Table, Portable for Reading Book (Wood)
   15. Laptop Stand with 360° Rotating Base, Height-Adjustable Laptop St...
   16. ITNRSIIET Mouse Pad with Stitched Edge, Premium-Textured Square M...
   17. Arae Laptop Stand for Desk, Adjustable Ergonomic Portable Aluminu...
   18. AOEVI Adjustable Laptop Stand with 360 Rotating Base, Computer St...
   19. Redragon IVY GCP500 Laptop Cooler - Support 12 to 15.6 Inch - 2 U...
   20. laptop sleeve 15.6'' case for laptop (black)
   21. Redragon INGRID GCP511 RGB Laptop Cooler – Support Up to 17.3 Inc...
   22. V2COM Laptop Screen Extender, 15.6 inch FHD 1080P IPS Laptop Moni...
   23. Aseem Laptop Stand, Adjustable Aluminum Laptop Computer Stand Tab...
   24. Dyazo Adjustable Laptop Stand, Portable Aluminum Laptop Holder Ad...
   25. Semiocthome Laptop Lap Tray Desk with Pillow Cushion, Lapboard wi...
   26. Genuine Fox Casual Laptop Case, Premium Winter Broadcloth Case fo...
   27. Genuine Fox Casual 15/15.6 Inch Laptop Bag Briefcase Ultra Premiu...

========================================
  PAGE 5  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=5
========================================
Found 27 products
    4. MCHOSE Adjustable Laptop Stand for Desk, Ergonomic Laptop Riser w...
    5. YM Sketch Holographic Laptop Sticker - Don't touch my Laptop| 3x6...
    6. Hossejoy foldable laptop table, breakfast serving bed tray, lap d...
    7. Zig-Zag Laptop Skin For 15inch Laptops-392
    8. Mehendi Design Laptop Skin for 14in Laptops
    9. For JERTECH KL333 Gaming Laptop Cooling Pad - 6x Blue LED Quiet F...
   10. Library Design Laptop Skin for 14 inch Laptops
   11. Voomy 6-Level Height Adjustable Foldable Laptop Stand, Compatible...
   12. Kotuday foldable portable aluminium laptop stand | desk stand wit...
   13. Laptop Stand, Laptop Holder Riser Computer Stand, Adjustable Plas...
   14. Dipelle UltraSlim 13 Inch Laptop Sleeve | Felt & PU Leather | Mac...
   15. Laptop Cooling Pad (ZR650) with Dual 140mm Silent Fans, LED Light...
   16. Zig-Zag Laptop Skin For 14in Laptops-257
   17. N-brand Laptop Stand Portable, Zinc Alloy Laptop Mini Stand, Lapt...
   18. Di Pelle™ Premium PU Leather & Soft Felt Laptop Sleeve Case Compa...
   19. Laptop Cooling Pad C7000, with 2 Large Silent Fans, Metal Mesh Su...
   20. Removable Vinyl Decal Sticker Skin for 14" inch Laptops/Unibody 1...
   21. YM Sketch Laptop Sticker - Totally flexiable| 6x6 cm area size, 1...
   22. Rahala Quilted PU Leather Laptop Sleeve – Slim & Elegant Laptop B...
   23. Standard ICE08 Cooling Pad Gaming Laptop Stand With Mobile Holder...
   24. Metal Laptop Stand, Aluminum Portable Laptop Cooling Desk Holder,...
   25. Premium Laptop Sleeve Case, Shockproof Protective Case, Soft Velv...
   26. Side Mount Clip on Laptop for Phone, Aluminum Alloy Computer Expa...
   27. Dipelle Premium Cobra PU Leather Laptop Sleeve with Front Zipper ...

========================================
  PAGE 6  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=6
========================================
Found 27 products
    8. 8-in-1 USB C Hub - Type-C to HDMI 4K@30Hz, USB 3.0 Ports, Etherne...
    9. Mobigon Professional Laptop Sleeve for 14-inch Laptops, Premium S...
   10. Genuine Fox Casual Laptop Sleeve Case Compatible with MacBook Air...
   11. Premium Laptop Sleeve Case, Shockproof Protective Case, Soft Velv...
   12. Black Woodgrain Design Matte Laptop Skin for 14in Laptops
   13. Adjustable Laptop Stand with USB Cooling Fan Quiet Ventilated Fol...
   14. HP Everyday - 14 inch Laptop Briefcase - A08JSAA - Odyssey Gray
   15. Premium Laptop Sleeve Case, Shockproof Protective Case, Soft Velv...
   16. Cougar-EGY printed laptop sleeve 15.6 & 15 inch Protective Case w...
   17. 14-15 Inch Waterproof Laptop Case Bag for Acer Chromebook 14, HP ...
   18. Solid Black Design laptop Skin for 15.7 inch laptops
   19. ICE08 Laptop Cooler – LCD Display with RGB Lighting & Full Contro...
   20. Rahala Protective 15.6-inch Laptop Sleeve - Stylish Design, Durab...
   21. Laptop Sleeve for Women – Waterproof, Padded for Perfect Protecti...
   22. Zig-Zag laptop Skin For 15 laptops-133
   23. Laptop Skins For 15-Inch Laptop-2275
   24. Dipelle™ Laptop Sleeve – Compatible with HUAWEI | MateBook 14, HP...
   25. Gshine Laptop Stand, Ergonomic Aluminum Laptop Computer Stand, Fo...
   26. Adjustable Ergonomic Laptop Stand for Desk - Portable Aluminum Co...
   27. Portal Lap Desk, Wooden Top Lap Desk With Pillow for Laptop Built...

========================================
  PAGE 7  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=7
========================================
Found 27 products
    4. DELL USB-C Charger 65W VT148 WMDHR for Latitude 7430 5330 7330 55...
    5. Dipelle Premium Cobra PU Leather Laptop Sleeve with Front Zipper ...
    6. Laptop Stand, Portable Aluminum 360° Adjustable Foldable Ventilat...
    7. Black Random Laptop Sleeve (13.3) Random Laptop Sleeve
    8. YM Sketch Laptop Sticker - ghabaa black| 6x6 cm area size, 1Pcs| ...
    9. Arae Laptop Stand for Desk, Adjustable Ergonomic Portable Aluminu...
   10. Vinyl Stickers - 6x6 cm Durable & Waterproof Decals for Laptops, ...
   11. 14-15 Inch Laptop Sleeve for HP Chromebook x360 14"/HP Pavilion x...
   12. TECHIE 1 Fan Laptop Cooling Pad with Hollow Heat Dissipation Desi...
   13. Energy Case ® 15.6 inch Laptop Sleeve Waterpoof Case for HP, Pavi...
   14. TECHZONE 3-in-1 Laptop & Screen Cleaning Kit | Electronics Cleane...
   15. Laptop Cooling Pad ZR650 With Led Light High Speed Fan Portable L...
   16. Laptop Cooling Pad C3000 With High Speed Fans Adjustable Stand Us...
   17. UGREEN - Foldable and adjustable metal-ventilated desktop laptop ...
   18. NILLKIN Mini Laptop Stand, Invisible Laptop Stand with Non-Slip S...
   19. KRESHU 360 Degree Rotatable Laptop Stand | Ergonomic Height Adjus...
   20. WiWU S500 Adjustable Aluminum Laptop Stand, Foldable Ergonomic Mu...
   21. YICOSUN Portable Aluminum Laptop Holder, with Cooling Fan,Adjusta...
   22. MXCOCO Portable Laptop Base, Foldable Laptop Stand with 10 Adjust...
   23. Dezllia Laptop Stickers - SSL/03 - Travelers Collection - For Lap...
   24. Chelory Water Resistant Shockproof Laptop Sleeve (Black, 15.6in)
   25. Butterfly Design Laptop Skin (15in)
   26. Wayona Aluminium Alloy Folding and Height Adjustable Stand Compat...
   27. Lenovo Casual Laptop Backpack , 15.6 inch Grey - GX40Q17227

========================================
  PAGE 8  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=8
========================================
Found 27 products
    7. E-train BG02B | Laptop Backpack Bag | Fits up to 15.6" Laptops wi...
    8. 40cm Keyboard Protector Film for Laptops
    9. ECVV Aluminum Laptop Stand for Desk, 6-Angles Adjustable Laptop R...
   10. GeekerChip 2nd 2.5'' SATA HDD SSD Hard Drive Disk DVD CD ROM Opti...
   11. Funny Laptop Sticker – Coffee Mood Character Design – Work Desk H...
   12. Funny Cartoon Cat Sticker Set – 2 Pieces Humorous To-Do List Desi...
   13. Vinyl Stickers - Durable & Waterproof Decals for Laptops, Phones,...
   14. Nillkin Bolster Plus Portable AdJustable High Desk Monitor Stand ...
   15. HP OMEN Gaming Business Water Resistant Backpack for 17.3'' Lapto...
   16. 4 in 1 Laptop Screen Protector Keyboard Mouse Pad 15.6 Inch Lapto...
   17. ICE06N Laptop Cooler – 6-Fan Cooling Stand with LED & USB
   18. Adjustable Laptop Stand,Multi-Angle Stand Portable Foldable Lapto...
   19. Aporia International - Stick on Laptop Invisible Foldable Side Ar...
   20. Laptop Cooling Pad Stand C6000 With 6 Quiet Fans Adjustable Heigh...
   21. Aluminum 9.5mm 2nd Hard Disk Drive Caddy Case Adapter For Univers...
   22. Laptop Stand: Adjustable, Multi-Angle Laptop Computer Stand for A...
   23. Cute Funny Cat Laptop Sticker – Minimal Peek Cat Design – Aesthet...
   24. Hand-boss Cleaning Suit for Laptop and LCD
   25. (Pack of 1) Utkrishtha Universal Silicone 14.0" Keyboard Protecto...
   26. Cleaning Kit - 3-in-1 Multi-Functional Set with Metal Pen Design,...
   27. Baseus Robust 240W Super Fast Cable Rapid Charging USB-C to USB-C...

========================================
  PAGE 9  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=9
========================================
Found 11 products
    4. Redragon GCP500 IVY Laptop Cooler - 5 Quiet fans - 2 USB Port - F...
    5. Scentiment Perfect Colors Aesthetic Art Stickers – 15 PCS Vintage...
    6. Multi-Functional Cleaner - 3-in-1 Tool with Metal Pen, Sponge, an...
    7. Hynix 2GB 2RX8 DDR2 800MHz PC2-6400s 200 PIN SO DIMM Laptop RAM M...
    8. UGREEN USB 2.0 A Male To 5-Pin Mini USB Male Gold-Plated Data Cab...
    9. ZERO Universal Laptop Charger, Compatible with Most Laptops and N...
   10. Digital Stylus Pen for H.P Envy/Spectre 2-in-1 Laptops, MPP Compa...
   11. 9.5mm /12.7mm Aluminum 2nd Second Hdd Caddy 9.5mm SATA 3.0 Optiba...

========================================
  PAGE 10  →  https://www.amazon.eg/s?k=laptops&i=electronics&page=10
========================================
Found 3 products

🏁 No new products on this page — scraping complete.

✅ Amazon scraping done — 193 products collected

,name,price,rating,reviews_count,screen_size,processor,ram,storage,gpu,url,image,source
0,Lenovo LOQ 15IRX9 Gaming Laptop - 13th Intel C...,"53,999.00",4.0,None,"15.6""",Intel Core i7-13650HX 14 Cores,None,512GB SSD,RTX 4050,https://www.amazon.eg/-/en/sspa/click?ie=UTF8&...,https://m.media-amazon.com/images/I/61wFLokn9R...,Amazon
1,"Lenovo LOQ 15IRX10 Gaming Laptop, Intel Core i...","68,999.00",None,None,"15.6""",Intel Core i7-14700HX,16GB,512GB SSD,RTX 5060,https://www.amazon.eg/-/en/sspa/click?ie=UTF8&...,https://m.media-amazon.com/images/I/71U2lhrNVM...,Amazon
2,MSI Katana 15 HX B14WFK (NVIDIA® GeForce RTX™ ...,"67,499.00",None,None,None,None,None,None,None,https://www.amazon.eg/-/en/sspa/click?ie=UTF8&...,https://m.media-amazon.com/images/I/71YTBqh1xe...,Amazon
3,"HP Laptop 14-em0025ne: Ryzen 5-7520U, 8GB Ram,...","19,999.00",4.2,None,"14""",Ryzen 5-7520U,8GB,None,None,https://www.amazon.eg/-/en/HP-Laptop-14-em0025...,https://m.media-amazon.com/images/I/51kHkSKx3q...,Amazon
4,ASUS Vivobook 14 [X1405VA-H005W] i5-13420H / 8...,"26,999.00",None,None,"14.0""",None,None,512GB SSD,None,https://www.amazon.eg/-/en/ASUS-Vivobook-X1405...,https://m.media-amazon.com/images/I/71u79SvGtA...,Amazon

## Cell 6 — Scrape Jumia Egypt
Scrapes up to **MAX_PAGES** pages from Jumia Egypt's laptop section using **URL-based pagination** (`?page=N#catalog-listing`).  
Note: Jumia does not display ratings/review counts on listing pages.

In [6]:
# ── Settings ──────────────────────────────────────────────────────
JUMIA_BASE_URL = "https://www.jumia.com.eg/laptops/"
MAX_PAGES      = 10          # Max pages to scrape (set to None for all pages)
# ──────────────────────────────────────────────────────────────────


def scrape_jumia(base_url=JUMIA_BASE_URL, max_pages=MAX_PAGES):
    """
    Scrape laptop listings from Jumia Egypt using URL-based pagination.

    Jumia appends ?page=N#catalog-listing to the base URL.
    Page 1  → https://…/laptops/
    Page 2  → https://…/laptops/?page=2#catalog-listing
    Page N  → https://…/laptops/?page=N#catalog-listing

    Parameters
    ----------
    base_url  : str  – Jumia laptops category URL (no page param)
    max_pages : int  – Maximum number of pages (None = scrape until end)

    Returns
    -------
    pd.DataFrame with columns:
        name, price, rating, reviews_count, screen_size,
        processor, ram, storage, gpu, url, image, source

    Note: Jumia listing pages do not expose rating / reviews_count;
          those fields will be None.
    """
    driver = get_driver()
    all_laptops = []
    seen_urls   = set()          # duplicate guard per run

    for page in range(1, (max_pages or 9999) + 1):
        page_url = base_url if page == 1 else f"{base_url}?page={page}#catalog-listing"

        print(f"\n{'='*40}")
        print(f"  PAGE {page}  →  {page_url}")
        print(f"{'='*40}")

        driver.get(page_url)

        try:
            WebDriverWait(driver, 20).until(
                EC.presence_of_element_located((By.CSS_SELECTOR, "article.prd"))
            )
        except Exception:
            print("⚠️  Timed-out waiting for products — stopping.")
            break

        time.sleep(3)
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)

        products = driver.find_elements(By.CSS_SELECTOR, "article.prd")
        print(f"Found {len(products)} products")

        if not products:
            print("⚠️  No products found — stopping.")
            break

        new_on_page = 0
        for idx, product in enumerate(products):
            try:
                try:
                    title = product.find_element(By.CSS_SELECTOR, "h3.name").text.strip()
                except Exception:
                    title = None

                try:
                    product_url = product.find_element(By.CSS_SELECTOR, "a.core").get_attribute("href")
                except Exception:
                    product_url = None

                # Deduplicate by URL (or title if URL missing)
                dedup_key = product_url or title
                if dedup_key and dedup_key in seen_urls:
                    continue
                if dedup_key:
                    seen_urls.add(dedup_key)
                    new_on_page += 1

                try:
                    price = product.find_element(By.CSS_SELECTOR, "div.prc").text.strip()
                except Exception:
                    price = None

                try:
                    image = product.find_element(By.CSS_SELECTOR, "img.img").get_attribute("src")
                except Exception:
                    image = None

                specs = extract_specs(title)

                all_laptops.append({
                    "name":          title,
                    "price":         price,
                    "rating":        None,   # Not available on listing page
                    "reviews_count": None,   # Not available on listing page
                    "screen_size":   specs["screen_size"],
                    "processor":     specs["processor"],
                    "ram":           specs["ram"],
                    "storage":       specs["storage"],
                    "gpu":           specs["gpu"],
                    "url":           product_url,
                    "image":         image,
                    "source":        "Jumia",
                })

                short_title = (title[:65] + "...") if title and len(title) > 65 else (title or "Unknown")
                print(f"  {idx+1:>3}. {short_title}")

            except Exception as e:
                print(f"  ⚠️  Product {idx+1} error: {e}")

        # No new products → Jumia didn't advance (last page repeated)
        if new_on_page == 0:
            print("\n🏁 No new products on this page — scraping complete.")
            break

    driver.quit()

    df = pd.DataFrame(all_laptops)
    print(f"\n✅ Jumia scraping done — {len(df)} products collected")
    return df


# ── Run ───────────────────────────────────────────────────────────
jumia_df = scrape_jumia()
jumia_df.head()

========================================
  PAGE 1  →  https://www.jumia.com.eg/laptops/
========================================
Found 40 products
    1. HP 14-em0025ne Laptop AMD Ryzen™ 5 7520U, 8GB Ram, 512GB SSD, AMD...
    2. HP Victus 15-fb3015ne Laptop - AMD Ryzen™ 7-7445HS - 16GB - 512GB...
    3. Lenovo Legion Go
    4. Asus TUF Gaming A15 FA506NCR-HN007W - AMD Ryzen 7-7435HS , 8GB RA...
    5. Asus LapTop TUF Gaming A15 FA506NCR-HN007W - 15.6 Inch - AMD Ryze...
    6. Asus Vivobook 16 Laptop, Intel® Core™ i7-13620H, 16GB Ram, 512GB ...
    7. Lenovo 83Dv008Qed-Loq 15Irx9 Intel® Core™ I7-13650Hx , Ram 16Gb ,...
    8. Lenovo Loq 15IAX9 Laptop, Intel® Core i5-12450HX, 12GB Ram, 512GB...
    9. Asus LapTop Vivobook S 15-S5507QA-MA037W - 15.6 3K OLED - Snapdra...
   10. MSI Thin A15 B7V Gaming Laptop, AMD Ryzen™ 7 7735HS, 16GB Ram, 51...
   11. Asus TUF F16 Gaming Laptop, Intel® Core™ 5 210H, 8GB Ram, 512 SSD...
   12. Asus TUF A16 Gaming Laptop, AMD Ryzen™ 7 260, 16GB Ram, 512GB SSD...
   13. HP Chromebook 14-inch HD Laptop, Intel Celeron N4000, 4 GB RAM, 3...
   14. Lenovo LOQ Laptop, AMD Ryzen™ 7 250, 16GB Ram, 512GB SSD, NVIDIA®...
   15. Lenovo Loq Laptop Intel Core i7-14700HX, 24GB Ram, 512GB SSD, NVI...
   16. Lenovo 14e Chromebook 81MH000BUS 14" Chromebook - 1920 x 1080 - A...
   17. Asus Vivobook 14 Laptop Snapdragon® X X1 26 100, 16GB Ram, 512GB ...
   18. HP OmniBook 3 Laptop 15-fn0001ne, AMD Ryzen™ AI 5 330, 16GB Ram, ...
   19. DELL Preowned Latitude 3390 2 IN 1 , 13.3 FHD X360 Touch Screen (...
   20. HP Pre-owned ProBook 650 G4 - Core i7-8650U - 8 GB Ram - 256 GB S...
   21. HP Victus15-fa1051ne Intel Core i5 13420H-8GB 3200Mhz DDR4- RTX 2...
   22. HP Pre-owned ProBook 650 G2 - Core i5-6200U - 8 GB Ram - 256 GB S...
   23. Asus TUF F16 Gaming Laptop, Intel® Core™ i7 14650HX, 16GB Ram, 51...
   24. DELL preowned Latitude 5420 – Core i5-1145G7 – 8GB RAM – 256GB SS...
   25. Asus Vivobook 16 Laptop, Intel® Core™ Ultra 5 225H, 16GB Ram, 512...
   26. DELL Pre-owned Latitude 7320 CORE I5 1135G7 - Ram 8G DDR4 - SSD 2...
   27. HP Stream 14-cb012wm, 14-inch HD display, Intel N3060, 4 GB RAM, ...
   28. Acer Chromebook 315 Laptop Intel Celeron N4500, 15.6-inch Full HD...
   29. TAGITOP Flip-Intel Core i5 8th Generation8259U-8 GB DDR4 RAM-256 ...
   30. Lenovo Pre-owned ThinkPad T14 Gen 1 -Like New - Core i7-10610U, 1...
   31. DELL Pre-owned Latitude 5580, 15.6 FHD (1920*1080) intel HD 630 u...
   32. DELL Pre-owned Latitude 5410, 14 FHD (1920*1080) intel UHD 4 GB, ...
   33. HP Victus 15-fa2318TX Intel Core i7-13620H-NVIDIA RTX 3050 6GB-16...
   34. Asus laptop E1504FA-NJ003W, AMD Ryzen 3 7320U, 256 GB SSD, 4 GB R...
   35. Lenovo LAPTOP-GAMING- LOQ 15IAX9E I5 12450HX 16G 512SSD RTX3050 6...
   36. DELL Preowned Vostro 3500 – Intel Core i3-1115G4, 8GB DDR4 RAM, 2...
   37. Asus Vivo book Go 15 E1504FA-NJ003W- AMD Ryzen3- 7320U, 4G Ram DD...
   38. Lenovo Pre-owned ThinkPad X13 -Like New - Core i5-1145G7 , 16GB D...
   39. DELL DELL inspiron 3530 Laptop - 13th Intel Core i5-1334U, 8GB RA...
   40. DELL Vostro 3530 i7-1355U 512GB SSD 8GB Ram Intel UHD Graphics 15...

========================================
  PAGE 2  →  https://www.jumia.com.eg/laptops/?page=2#catalog-listing
========================================
Found 40 products
    1. Asus Chromebook C523, 15.6-inch FHD NanoEdge display with 180-deg...
    2. Asus Vivobook 16 X1605VA-ACH005W ( Core i5-13420H, 16G Ram DDR4, ...
    3. Lenovo Thinkpad E16 Gen3 -Intel Core Ultra 7 255H, 16C, 16GB Ram ...
    4. HP fd0021nx Intel Core i3-1315U 256GB SSD 4GB Ram Intel UHD Graph...
    5. MSI LAPTOP Cyborg 15 A2RUDX CPU Core 7 240H RAM16G DDR5 8GB*2 SSD...
    6. DELL Pre-owned XPS13 - 9310 – Core i7-1185G7 - Ram 16GB RAM, Hard...
    7. Asus Vivobook Go 15 E1504FA-BQ8233W ( AMD Ryzen3-30, 8G Ram LPDDR...
    8. HP LAPTOP OmniBook 5 Flip14-fp0050ne, Intel Core 5-210U, 8GB LPDD...
    9. Lenovo Thinkpad E16 Gen3 ( Intel Core Ultra 7 255H, 16GB Ram DDR5...
   10. Lenovo LAPTOP-ideapad 3 slim 15IRH10 -i5-13420H-8G-512SSD 83K100E...
   11. Lenovo Legion 5 15IAX10 ( Intel Core Ultra 7 255HX, 2x 16GB Ram D...
   12. Lenovo Legion 5 15IAX10 Laptop - Intel Core™ Ultra 9-275HX - 32GB...
   13. Asus Vivobook 16-X1605VA-OACH007W ( Core i7 13620H, 16G Ram, 512G...
   14. Asus ROG Strix G16 G614FR-G4032W ( AMD Ryzen9 9955HX, 32GB Ram DD...
   15. Lenovo IdeaPad Slim 3 15IRH10 ( Core i5-13420H, 16G Ram DDR5, 512...
   16. Lenovo LOQ 15IAX9E (Essential) Gaming - Intel Core i5-12450HX, NV...
   17. Lenovo LOQ 15IAX9E (Essential) Gaming - Intel Core i5-12450HX, NV...
   18. Lenovo LENOVO LOQ 15AHP10 AMD RYZEN 7 250 Luna grey 15.6 FHD 144H...
   19. Apple MacBook Air 13 M5 10C CPU 8C GPU / 16GB / 512GB / Sky Blue ...
   20. Asus TUF Gaming F16 2025 FX608JHR-RV057W Gaming Laptop Intel Core...
   21. MSI Crosshair 16 HX AI D2XWFKG (NVIDIA® GeForce RTX™ 5060 Laptop ...
   22. HP Victus 15-fa1082wm Intel Core i5-13420H NVIDIA GeForce RTX 405...
   23. Asus ROG Strix G16 G614PR-RV009W ( AMD Ryzen9 8940HX, 32GB DDR5-5...
   24. HP Envy x360 14-es1013dx (9R8R2UA) – 2in1 Convertible Laptop – In...
   25. Asus Vivobook Go 15 E1504FA-BQ085W ( AMD Ryzen 5-7520U, 8G Ram LP...
   26. Apple MacBook Air 15 M4 10C CPU 10C GPU / 16GB / 256GB / AR
   27. Lenovo Pre-owned ThinkPad X1 Xtreme Carbon - Core i7-8850H - Ram ...
   28. Lenovo Pre-owned ThinkPad E14 - Like New - Intel Core i5-10210U, ...
   29. Lenovo LOQ 15IRX9 Core i5-13450HX RAM 16G DDR5 4800 HDD 512GB SSD...
   30. Lenovo LENOVO LOQ 15AHP10 GAMING CPU AMD Ryzen 7 250 RAM 16GB DDR...
   31. MSI Katana 15 HX-B14WFK Laptop - Intel® Core™ i7-14700HX - 16GB -...
   32. Apple MacBook Air 15 M3 8C CPU 10C GPU / 8GB / 256GB / Midnight/ ...
   33. Lenovo LAPTOP Legion 5 15AHP10 CPU AMD Ryzen 7 260 RAM 32GB DDR5-...
   34. Asus Laptop Vivobook S14 OLED M5406UA-QD055W - AMD Ryzen 9 8945HS...
   35. Lenovo IdeaPad Slim 3 15IRH10 Core i5-13420H RAM 16G DDR5 4800 HD...
   36. DELL Vostro 3530 ( Core I7-1355U12 MB Cache 10- 8GB Ram DDR4-3200...
   37. Lenovo LAPTOP LOQ 15IAX9E Laptop, Intel Core i5-12450HX, 512GB SS...
   38. DELL Preowned Vostro 5401 Core i5-1035G1 - Ram 8GB - Hard 256GB S...
   39. MSI Thin 15 B13UCX ( Core i5-13420H-8GB Ram DDR4-3200-512GB NVMe-...
   40. Lenovo Ideapad Flex 5 - x360 Intel Core-i5-1235U , 8GB, 512 SSD, ...

========================================
  PAGE 3  →  https://www.jumia.com.eg/laptops/?page=3#catalog-listing
========================================
Found 40 products
    1. Asus Vivobook Go 15 E1504FA-BQ8233W AMD Ryzen 3 30 256GB PCIE G3 ...
    2. Apple MacBook Pro 16 M3 Pro 12C CPU 18C GPU / 36GB / 512GB / EN /...
    3. HP OmniBook 5 Flip 14-FP0023DX 2 In 1 Intel Core 7 150U 512GB SSD...
    4. Lenovo LOQ essential 15IAX9E 83LK0070ED Intel Core i5-12450HX - N...
    5. Lenovo Yoga 7 2-in-1 14ILL10 – Intel Core Ultra 7 258V - 32GB Ram...
    6. Acer PREDATOR HELIOS NEO 16-PHN16-72-73U2 - Intel Core i7-14650HX...
    7. Lenovo LOQ 15IRX9 Laptop - Intel Core™ i5-13450HX - 16GB - 512GB ...
    8. HP Victus 16-r1042ne Gaming Laptop, Intel Core i7-14700HX, 16GB D...
    9. Lenovo LAPTOP-ideapad slim3 15IRH10 I7 13620H 8G 512SSD 83K100AXA...
   10. Lenovo LOQ 15IRX9 Gaming Laptop Intel Core I7-13650HX 512GB SSD 1...
   11. Asus Vivobook 15 X1504VA-BL823W ( Core i3-1315U, 8GB Ram, 256GB N...
   12. Lenovo Renewed ThinkPad E15 Gen2- Intel Core i3-1115G4 , Ram 8GB ...
   13. DELL DELL Vostro 3530 Core i7 1355U Laptop - 8GB RAM, 512GB SSD, ...
   14. Lenovo IdeaPad Slim 3 15IRH10 Core i5-13420H RAM 16G DDR5 4800 HD...
   15. Apple MacBook Pro 14 M3 Pro 11C CPU 14C GPU / 18GB / 512GB / EN /...
   16. HP Victus 15-fa2032ne - Intel Core i5-13450HX - 8GB - 512GB SSD -...
   17. Apple MacBook Pro 14 M4 10C CPU 10C GPU / 16GB / 1TB / Silver / A...
   18. DELL DELL Latitude 3440 Laptop, 14" FHD IPS 60Hz Display, Intel C...
   19. HP OmniBook 5 Laptop AI 16-af1017wm ( Intel Core Ultra 7 255U, 16...
   20. Lenovo IdeaPad Slim 3 15IRH10 Laptop, Intel Core™ i5-13420H, 16GB...
   21. Asus Vivobook 14 X1407QA-LY045W Snapdragon X X1 26 100 14” IPS WU...
   22. HP laptop OmniBook 3 Laptop Next Gen AI 15-fn0001ne (C65XSEA)
   23. Lenovo LOQ 15IAX9 ( Core i5-12600HX, 16GB Ram DDR5-4800, 512GB NV...
   24. Lenovo LAPTOP-ideapad slim315IRH10 I7 13620H 16 512SSD 83K100F0ED...
   25. Asus Vivobook 15 X1504VA-BQ4615W Intel Core 5 120U 512GB M.2 NVMe...
   26. HP ProBook 460 G11 Laptop Intel Core Ultra 7 155H 512GB SSD 8GB R...
   27. MSI Raider 18 HX AI A2XWJG (NVIDIA® GeForce RTX™ 5090 Laptop GPU,...
   28. DELL DELL Precision 3580 Mobile Workstation Laptop - 15.6" FHD, I...
   29. Asus TUF Gaming F16 FX607VJB-RL165W Gaming Laptop Intel Core 5 21...
   30. Lenovo LAPTOP-GAMING- LOQ 15IRx9 I5 13450HX 16G 512SSD RTX3050 6G...
   31. HP Victus 15-fa2035ne Laptop - Intel Core™ i7-13620H - 16GB - 512...
   32. HP Laptop 14-em0003ne (D00Z3EA)
   33. Lenovo LAPTOP--GAMING- LOQ 15IRx9 I5 13450HX 24G 512SSD RTX3050 6...
   34. Asus TUF F16 FX608JHR-RV057W ( Core i7-14650HX, 16G Ram DDR5, 512...
   35. Asus Asus Vivobook 16 X1605VA-OACH565W - Intel® Core™ i5-13420H -...
   36. DELL Vostro 15 3530 – Core i5-1334U, 8G Ram DDR4-3200- 512G NVMe,...
   37. Asus Vivobook 16 X1607QA-MB155W ( Snapdragon X X1 26 100, 16G Ram...
   38. Lenovo Legion 5 15IRX10 – Core i7-13650HX, 2x 12GB Ram DDR5-4800,...
   39. Lenovo Legion Pro 7 16IAX10H Gaming Laptop Intel Core Ultra 9 275...
   40. Lenovo IdeaPad Slim 3 15IRH10 ( Core i7-13620H-16G Ram DDR5-4800-...

========================================
  PAGE 4  →  https://www.jumia.com.eg/laptops/?page=4#catalog-listing
========================================
Found 40 products
    1. Asus Vivobook S14 S3407QA-SF067W Snapdragon X X1 26 100 512GB M.2...
    2. MSI Vector 17 HX AI A2XWJG Gaming Laptop Intel Core Ultra 9 275HX...
    3. HP Victus 15-fa2013dx Intel Core i5-13420H - NVIDIA RTX 3050 6GB ...
    4. Lenovo IdeaPad 3 14IML05 Intel Core i5-10210U 1TB HDD 5400rpm 2.5...
    5. Asus TUF Gaming A15 FA506NCG-HN807W ( AMD Ryzen 7-7445HS, 8GB Ram...
    6. Fujitsu Lifebook U9311 - I7 1185G7-16GB-512GB SSD- Win 10 - Red
    7. Lenovo ThinkPad E14 Gen 7 ( Intel Core Ultra 7 255H, 16GB Ram DDR...
    8. Acer Predator Helios Neo 16 PHN16-72-99PA – Intel Core i9-14900HX...
    9. Lenovo LOQ 15IRX9 Gaming Laptop - 13th Intel Core i7-13650HX 14 C...
   10. Asus TUF Gaming A16 2025 FA608PM-RV169W Gaming Laptop, AMD Ryzen ...
   11. MSI LAPTOP Katana 15 HX B14WEK Black Intel Core i7-14650HX RAM 16...
   12. Lenovo IdeaPad Slim 3 – 83K100F1ED – i7-13620H – 8GB DDR5 – 512GB...
   13. HP LAPTOP AI 15-fd2000ne , Intel Core Ultra 5 225U Processor, 15....
   14. Lenovo LOQ 15AHP10 Gaming Laptop with LA1 Ai Chip NVIDIA GeForce ...
   15. MSI Katana 15 HX B14WEK Laptop Intel Core i714700HX 16GB 512GB SS...
   16. Asus Zenbook 14 UM3406GA-QL157W ( AMD Ryzen AI 7 445, 16G Ram LPD...
   17. Apple MacBook Air 13 M4 10C CPU 8C GPU / 16GB / 256GB / AR / sky ...
   18. Lenovo LOQ 15AHP10 Laptop AMD Ryzen™ 7 250, 16GB Ram, 512GB SSD, ...
   19. Asus Vivobook 15 X1504VA-BQ4615W ( Intel Core 5 120U, 8G Ram DDR5...
   20. MSI LAPTOP Summit 16 AI Evo A2HMTG CPU Ultra 7 255H RAM LP DDR5 1...
   21. DELL Laptop inspiron 14 7440 2 in 1 Laptop, 14 Inch FHD Touch, In...
   22. Lenovo LAPTOP-GAMING- LOQ-15IRX9-I7-13650HX 16G-512SSD-RTX3050 6G...
   23. HP VICTUS 16-R1078NE ( Core i5-14450HX, 16GB Ram DDR5-5600, 512GB...
   24. Asus ROG Strix G16 G614PH-RV161W - AMD Ryzen 9 8940HX - NVIDIA Ge...
   25. Asus TUF Gaming A15 FA506NCQ-HN167W - AMD Ryzen 7 170 - NVIDIA Ge...
   26. Asus Vivobook 16 X1605VA-ACH007W ( Core i7 13620H, 16GB Ram DDR4,...
   27. Asus TUF Gaming F16 FX607VJB-RL165W ( Core 5 210H, 16GB Ram DDR4,...
   28. Lenovo LOQ 15IRX9 ( Core i7-13650HX, 16G Ram DDR5-4800, 512GB NVM...
   29. MSI Cyborg 15 A2RUDX Gaming Laptop Intel Core 7-240H 512GB SSD 16...
   30. HP 14-em0024ne Laptop AMD Ryzen™ 3 7320U, 8GB Ram, 256GB SSD, AMD...
   31. MSI Katana 15 HX B14WFK Gaming Laptop Intel Core i7-14700HX 1TB N...
   32. Lenovo Legion 5 15IAX10-83F00072ED- Intel Core Ultra 9 275HX–RAM ...
   33. Asus TUF Gaming F16 FX607VJB-RL805W Intel Core 5 210H - Nvidia RT...
   34. Acer Aspire Go 16 AG16-71P-57MD Intel Core 5 120U 512GB SSD 16GB ...
   35. Asus TUF F16 FX608JMR-RV017W ( Core i7-14650HX, 16GB Ram DDR5 560...
   36. MSI Vector 16 HX AI A2XWHG (NVIDIA® GeForce RTX™ 5070 Ti Laptop G...
   37. Asus VivoBook S14 Thin and Light Laptop, 14.0-inch, WUXGA (1920 x...
   38. MSI Katana 15 HX B14WEK-832 - Intel Core i7 14650HX - NVIDIA RTX ...
   39. Asus Vivobook 16 X1607QA-MB054W Snapdragon X X1 26 100 1TB M.2 NV...
   40. DELL Vostro 3530 - 13th Intel Core i3-1305U, 8GB RAM, 512GB SSD, ...

========================================
  PAGE 5  →  https://www.jumia.com.eg/laptops/?page=5#catalog-listing
========================================
Found 40 products
    1. Lenovo LAPTOP Ryzen 5 7235HS - 16GB - 512SSD - RTX 3050-15.6" FHD...
    2. Lenovo Thinkpad E16 Gen3 ( Intel Core Ultra 5 225U, 16GB Ram DDR5...
    3. Asus Vivobook 14 X1407QA-LY045W ( Snapdragon X X1 26 100, 16G Ram...
    4. Lenovo Laptop IDEAPAD5 (2 IN 1) - Intel Core 7, 16GB RAM, 512GB S...
    5. MSI Crosshair 16 HX AI D2XWGKG Laptop - Intel Core™ Ultra 7-255HX...
    6. Asus TUF Gaming F16 FX607VJ-RL805W ( Core 5 210H, 8GB Ram DDR4 56...
    7. Lenovo Legion 5 15IRX10 Laptop - Intel Core™ i7-13650HX - 16GB - ...
    8. Asus Vivobook S14-S3407CA-LY065W - Intel Core Ultra 5 225H - INTE...
    9. Asus TUF Gaming A16 FA608UH-RV007W AMD Ryzen 7 260 - NVIDIA RTX 5...
   10. Lenovo Legion 5 Laptop, Intel® Core Ultra 9 275HX, 32GB Ram, 1TB ...
   11. DELL Laptop inspiron 14 7440 2 in 1 Laptop, 14 Inch FHD Touch, In...
   12. Lenovo LOQ essential 15IAX9E 83LK0076AD Intel Core i5-12450HX - N...
   13. Lenovo Legion Pro 5 16IRX10 – Core i7-14650HX, 16GB Ram DDR5-5600...
   14. DELL Pro 16 Core Ultra 5 235U - 8GB RAM - 512GB SSD - 16-inch -In...
   15. HP Laptop ProBook 460, Intel Core Ultra 5 125U, 16-inch, 8GB DDR5...
   16. MSI LAPTOP (9S7-15M352-070) Vector 16 HX AI A2XWHG Core Ultra 9 2...
   17. Lenovo LOQ 15IRX10 ( Core i7-13650HX, 16GB Ram DDR5, 512GB NVMe, ...
   18. Lenovo LAPTOP-GAMING- LOQ 15IRx9 I5 13450HX 16G 512SSD RTX3050 6G...
   19. Asus TUF Gaming F16 FX607VJB-RL805W Gaming Laptop Intel Core 5 21...
   20. Asus Zenbook 14 UX3405CA-SU319W Intel Core Ultra 9 285H 1TB Nvme ...
   21. Lenovo LOQ 15IRX9 83DV008QED - Intel® Core™ i7-13650HX - NVIDIA® ...
   22. Asus Zenbook 14 UX3405CA-PZ009W Intel Core Ultra 9 285H 1TB M.2 N...
   23. Asus Vivobook S14 Flip TP3402VA-LZ065W Intel Core i5-13420H - Int...
   24. Lenovo LOQ 15IRX10 – Core i7-14700HX-24G Ram DDR5-4800- 512 GB NV...
   25. HP LAPTOP-OMEN-Gaming 16 ULTRA7 AM0026NE 255H 16G 512 RTX 5050 8G...
   26. HP (Upgraded Version) Envy X360 14-es1023dx Touchscreen Laptop Wi...
   27. Lenovo Legion Pro 5 16IAX10 - Intel Core Ultra 7 255HX, 16GB Ram ...
   28. Lenovo LOQ 15IRX9 Laptop - Intel Core™ i5-13450HX - 24GB - 512GB ...
   29. Asus ROG Strix G16 G614FM-RV169W -AMD Ryzen9 9955HX, 16GB DDR5 48...
   30. Asus TUF Gaming F16 FX608JHR-RV057W Gaming Laptop Intel Core i7-1...
   31. Lenovo LOQ 15IRX9 Gaming Laptop - 13th Intel Core i7-13650HX 14 C...
   32. Asus ROG Strix G16 G614FM-RV169W -AMD Ryzen9 9955HX, 16GB DDR5 , ...
   33. Asus TUF Gaming A16 FA608UH-RV007W - AMD Ryzen7 260- 16GB DDR5-56...
   34. Asus TUF Gaming F16 FX608JMR-RV017W Gaming laptop Intel Core i7 1...
   35. Asus Vivobook 14 Filp TP3407SA-SG157W ( Ultra7 256V, 16G Ram LPDD...
   36. Lenovo IdeaPad Slim 3 15IRH10 – Core i7-13620H, 16G Ram DDR5-4800...
   37. HP Spectre x360 2-in-1 Laptop 16-aa0013dx – Intel Core Ultra 7 15...
   38. MSI Katana 15HX-B14WGK Intel Core i7-14700HX - 16GB - 512GB SSD -...
   39. Asus TUF Gaming F16 2024 FX607VJB-RL805W Gaming Laptop, Intel Cor...
   40. MSI Laptop Crosshair 16 HX AI D2XWGKG Intel Ultra 7 255HX RTX 507...

========================================
  PAGE 6  →  https://www.jumia.com.eg/laptops/?page=6#catalog-listing
========================================
Found 40 products
    1. TAGITOP PLUSII-Intel Core i7 10th Generation 10510U-8 GB DDR-4 RA...
    2. Asus TUF Gaming A14 FA401UU-RG028W - AMD Ryzen7 8845HS, 16GB LPDD...
    3. HP Spectre X360 16-f2023dx (Core I7-1360P 3.70GHz, 16GB Ram-1TB N...
    4. Lenovo IdeaPad Slim 3 15IRH10 – Core i7-13620H, 16G Ram DDR5-4800...
    5. Lenovo LOQ 15AHP10 ( AMD Ryzen 7 250, 16GB Ram DDR5-5600, 512GB N...
    6. Lenovo IdeaPad Slim 3 15IRH10 – Core i7-13620H- 16G Ram DDR5-4800...
    7. Lenovo Ideapad Pro 5 16IMH9 ( Intel Core Ultra 5 125H 14Core-4.5H...
    8. Lenovo LOQ 15IRX10 ( Core i7-14700HX, 16GB Ram DDR5, 512GB NVMe, ...
    9. Asus ROG Strix G16 G615LW-RV132W ( Ultra 9 275HX, 32GB DDR5-5600M...
   10. Lenovo LAPTOP--GAMING- LOQ 15IRX10 I7 13700HX 24G 512SSD RTX5060 ...
   11. DELL Latitude 5520 Laptop With 15.6 Inch HD Display, Core i5-1135...
   12. Asus ROG Strix G16 G614PR-RV161W ( AMD Ryzen9 8940HX, 16GB DDR5-5...
   13. Lenovo LOQ Essential 15IRX11 ( Core i7-13650HX, 16GB Ram DDR5-480...
   14. Asus Vivobook 16 X1605VA-OACH565W (Core i5-13420H, 16G Ram DDR4, ...
   15. Lenovo LOQ 15IAX9E Essential 83LK00C9US - Intel Core™ i5-12450HX ...
   16. Asus ROG Flow Z13 GZ302EA-RU016W- AMD Ryzen AI MAX+ 395, 32GB LPD...
   17. Asus ROG Strix SCAR 18 G835LR-AI3201W Gaming Laptop Intel Core Ul...
   18. Lenovo Yoga Pro 7 14IMH9- Core Ultra 7 155H, 16C, 16GB LPDDR5x-74...
   19. MSI Crosshair 16 HX AI D2XWFKG Gaming Laptop, Intel Core Ultra 7 ...
   20. Asus TUF F16 FX607VU-RL007W ( Core i7-13620H, 16GB Ram DDR5-5600,...
   21. Asus Vivobook 16-X1605VA-OLED507W ( Core i7 13620H, 16GB Ram DDR4...
   22. Lenovo Yoga 7 2-in-1 14IML9- Intel Core Ultra 7 155H- 16GB Ram LP...
   23. HP Laptop AI 15-fd2001ne (C53H7EA)
   24. HP Victus 15-fa2031ne ( Core i7-14650HX, 16G Ram DDR5-5600, 512GB...
   25. Lenovo LOQ 15ARP9 ( AMD Ryzen 7 7435HS, 12GB Ram DDR5-4800, 512GB...
   26. Asus Zenbook 14-UX3405CA-PZ009W ( Ultra 9-285H, 32GB Ram LPDDR5X,...
   27. Lenovo LOQ 15IRX9 Gaming Laptop with LA1 Ai Chip NVIDIA GeForce R...
   28. Lenovo LOQ 15IRX10 ( Core i7-13700HX, 16GB Ram DDR5-4800, 512GB N...
   29. Asus TUF Gaming A15 FA506NCQ-HN167W Gaming Laptop AMD Ryzen 7 170...
   30. Asus VivoBook Flip S14 Thin and Light 2-in-1 Laptop, 14 Inch Touc...
   31. HP 15-FD0557NIA Laptop, Intel Core i7-1355U Processor, 15.6 Inch ...
   32. Asus Vivobook 14 X1407QA-LY045W Snapdragon X X1 26 100 512GB M.2 ...
   33. MSI Katana 15 HX B14WGK Laptop Intel Core i714700HX 16GB 512GB SS...
   34. HP Victus 15-FA1039NE Gaming Laptop Intel Core i7-13700H 512 GB P...
   35. Lenovo Thinkpad E16 Gen3 – Intel Core Ultra 5 225U, 8GB Ram DDR5-...
   36. Asus TUF Gaming A14 FA401WV-RG053W - AMD Ryzen AI 9 HX 370, 16GB ...
   37. Asus Vivobook 16 X1605VA-OLED507W Intel Core I7-13620H 512GB M.2 ...
   38. MSI NB-MSI Prestige 13 AI Evo A1MG-Intel Ultra 7 155H-13Q2 Intel ...
   39. Lenovo LAPTOP Legion 5 15IAX10 CPU Ultra 7 255HX RAM 32G DDR5 1TB...
   40. Asus Vivobook 16 X1607CA-MB117W Intel Core Ultra 7 255H 1TB M.2 N...

========================================
  PAGE 7  →  https://www.jumia.com.eg/laptops/?page=7#catalog-listing
========================================
Found 40 products
    1. Asus ROG Strix SCAR 18 G835LR-AI3201W ( Ultra 9 275HX, 32GB Ram D...
    2. Asus Vivobook 15 X1504VA-BQ4616W ( Core 5 120U, 16GB Ram DDR5, 51...
    3. Lenovo LOQ 15ARP9 ( AMD Ryzen 5 7235HS, 16GB Ram DDR5-4800, 512GB...
    4. Lenovo IdeaPad Slim 3 15IRH10 Intel Core i5-13420H 512GB SSD M.2 ...
    5. Asus V16 V3607VJ-RP007W ( Core 7 240H, 16GB Ram DDR5-5600, 512GB ...
    6. Asus TUF Gaming A16 FA608PM-RV169W ( AMD Ryzen9 8940HX, 16GB DDR5...
    7. Asus ROG Strix G16 G615LM-RV009W - Intel Core Ultra 9 Processor 2...
    8. MSI Vector 16 HX AI A2XWIG -Intel® Core Ultra 9 275HX 1TB NVMe PC...
    9. Lenovo Legion 5 15IRX10 83LY00PCED Gaming Laptop Core i7-13650HX ...

,name,price,rating,reviews_count,screen_size,processor,ram,storage,gpu,url,image,source
0,"HP 14-em0025ne Laptop AMD Ryzen™ 5 7520U, 8GB ...","EGP 24,869.00",None,None,None,None,8GB,512GB SSD,None,https://www.jumia.com.eg/hp-14-em0025ne-laptop...,https://eg.jumia.is/unsafe/fit-in/300x300/filt...,Jumia
1,HP Victus 15-fb3015ne Laptop - AMD Ryzen™ 7-74...,"EGP 46,689.00",None,None,None,None,None,512GB SSD,None,https://www.jumia.com.eg/hp-victus-15-fb3015ne...,https://eg.jumia.is/unsafe/fit-in/300x300/filt...,Jumia
2,Lenovo Legion Go,"EGP 42,559.00",None,None,None,None,None,None,None,https://www.jumia.com.eg/lenovo-legion-go-1077...,https://eg.jumia.is/unsafe/fit-in/300x300/filt...,Jumia
3,Asus TUF Gaming A15 FA506NCR-HN007W - AMD Ryze...,"EGP 40,599.00",None,None,None,Ryzen 7-7435HS,8GB,512GB SSD,RTX 3050,https://www.jumia.com.eg/asus-tuf-gaming-a15-f...,https://eg.jumia.is/unsafe/fit-in/300x300/filt...,Jumia
4,Asus LapTop TUF Gaming A15 FA506NCR-HN007W - 1...,"EGP 37,999.00",None,None,"15.6""",Ryzen 7 - 8GB,None,512GB SSD,RTX3050,https://www.jumia.com.eg/asus-laptop-tuf-gamin...,https://eg.jumia.is/unsafe/fit-in/300x300/filt...,Jumia

## Cell 7 — Merge all results & save to CSV

Combines whichever DataFrames exist (`noon_df`, `amazon_df`, `jumia_df`) into a  
single file called **`all_laptops.csv`**.

> If you only ran one or two scrapers, the missing DataFrames are simply skipped.

In [8]:
# ── Collect whichever DataFrames were created ────────────────────
available = {}
for name, var in [("Noon", "noon_df"), ("Amazon", "amazon_df"), ("Jumia", "jumia_df")]:
    try:
        df_check = eval(var)
        if not df_check.empty:
            available[name] = df_check
            print(f"  ✅ {name:<8} — {len(df_check):>4} products")
        else:
            print(f"  ⚠️  {name:<8} — DataFrame is empty, skipping")
    except NameError:
        print(f"  ℹ️  {name:<8} — not scraped yet, skipping")

if not available:
    print("\n❌ No data to merge. Run at least one scraper first.")
else:
    OUTPUT_FILE = "all_laptop.csv"

    combined = pd.concat(available.values(), ignore_index=True)

    combined.to_csv(OUTPUT_FILE, index=False, encoding="utf-8-sig")

    print(f"\n{'─'*40}")
    print(f"  Total products : {len(combined)}")
    print(f"  Saved to       : {OUTPUT_FILE}")
    print(f"{'─'*40}")

    combined.head(10)

  ✅ Noon     —  500 products
  ✅ Amazon   —  193 products
  ✅ Jumia    —  370 products

────────────────────────────────────────
  Total products : 1063
  Saved to       : all_laptop.csv
────────────────────────────────────────